### ISSUE TITLE
hardhat-waffle: changeTokenBalance matcher not available

### ISSUE THREAD

**Issue by ItsNickBarry** [nomiclabs/hardhat#1020]
Attempting to use the Waffle chai matcher `changeTokenBalance` returns this error: 

```
Invalid Chai property: changeTokenBalance
```

For example:

```javascript
const { expect } = require('chai');

await expect(
  () => instance['mint(address,uint256)'](receiver.address, amount)
).to.changeTokenBalance(
  instance, receiver.address, amount
);
```

`@nomiclabs/hardhat-waffle` 2.0.0
`ethereum-waffle` 3.2.0

**Comment by dahifi** [comment]
Having same issue with `changeEtherBalance`. Same version of waffle.

**Comment by dahifi** [comment]
For those wondering how to get ether balance, there are two ways to do it:

For contracts, you'll have to use `ethers.provider.getBalance(contract.address));`. Addresses that are signers objects from `ether.getSigners()` can use the `getBalance()` method, as in:

```
const {wallet1, wallet2} = await ethers.getSigners();
console.log("Wallet1 balance: ", await wallet1.getBalance());
```

Until this bug is fixed, you'll have to query the wallet balance before the changing call, then again after, then compare the two. 

```
const before = await ethers.provider.getBalance(auction.address);
console.log("Before: ", before.toHexString());
await expect(auction.deposit_pot({value: 1}));
const after = await ethers.provider.getBalance(auction.address);
console.log("After: ", after.toHexString());
console.log("Difference: ", before.sub(after).toHexString());
>Before:  0x00
>After:  0x01
>Difference:  -0x01
```
Note that the balances changes on wallets will also include gas. 

I really hope there's a resolution on this soon.

**Comment by Skyge** [comment]
Have a same error: `Error: Invalid Chai property: changeTokenBalance`
```js
const { expect } = require("chai");
const { ethers, waffle } = require("hardhat");
const { deployContract } = waffle;

const Token = require("../artifacts/contracts/mock/Token.sol/Token.json");

describe('DLToken', () => {
    let token;
    let user1, user2;

    before(async () => {
        const [owner, ...accounts] = await ethers.getSigners();
        user1 = accounts[0];
        user2 = accounts[1];
        token = await deployContract(owner, Token, ["Mock Token", "MT"]);
    });

    it('mint', async () => {
        expect(await token.balanceOf(user1.address)).to.equal(0);
        await expect(() =>  token.connect(user1).mint(user1.address, 100)).to.changeTokenBalance(token, user1, 100);
    });
});
```

**Comment by gitpusha** [comment]
also doesnt work for `changeEtherBalance` (see #1061 )

**Comment by dahifi** [comment]
Looks like there are some functions missing in the https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-waffle/src/waffle-chai.ts file, I'll take a crack and see if I can get these to work.

**Comment by StErMi** [comment]
It seems that `changeEtherBalance` is not working with the contract's address.

I've tried this test:

```
const tx = rent.connect(renter1).stakerPayout();
await expect(tx).to.emit(rent, 'StakerPayout').withArgs(renter1.address, stakerFeeBalance);
await expect(await tx).to.changeEtherBalance(stake.address, stakerFeeBalance);
```

and `changeEtherBalance` fails with this error

```
     TypeError: Provider not found
      at Object.ensure (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/calledOnContract/utils.js:6:15)
      at getBalanceChange (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/changeEtherBalance.js:25:13)
      at Proxy.<anonymous> (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/changeEtherBalance.js:11:13)
      at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
      at Context.<anonymous> (test/rent.ts:273:33)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)
```

am I doing something wrong?

I'm using these lib versions

```
    "@nomiclabs/hardhat-ethers": "^2.0.0",
    "@nomiclabs/hardhat-etherscan": "^2.1.6",
    "@nomiclabs/hardhat-solhint": "^2.0.0",
    "@nomiclabs/hardhat-waffle": "^2.0.0",
    "@openzeppelin/contracts": "^4.4.1",
    "@typechain/ethers-v5": "^7.0.1",
    "@typechain/hardhat": "^2.3.0",
    "@types/chai": "^4.2.21",
    "@types/mocha": "^9.0.0",
    "@types/node": "^16.9.1",
    "chai": "^4.3.4",
    "dotenv": "^10.0.0",
    "ethereum-waffle": "^3.0.0",
    "ethers": "^5.0.0",
    "hardhat": "^2.6.4",
    "prettier": "^2.4.0",
    "prettier-plugin-solidity": "^1.0.0-beta.18",
    "solhint": "^3.3.6",
    "solhint-plugin-prettier": "^0.0.5",
    "solidity-coverage": "^0.7.17",
    "ts-node": "^10.2.1",
    "typechain": "^5.1.2",
    "typescript": "^4.4.3"
```

**Comment by ItsNickBarry** [comment]
The matcher expects a contract instance, not an address.

**Comment by Vivraan** [comment]
This is still an issue in `@nomiclabs/hardhat-waffle@2.0.2` and `ethereum-waffle@3.4.0`.

**Comment by CryptoKiddies** [comment]
> This is still an issue in `@nomiclabs/hardhat-waffle@2.0.2` and `ethereum-waffle@3.4.0`.

Are you using human-readable ABI when instantiating contract @Vivraan? I think the issue exists in this case.
