### ISSUE TITLE
HRE error: Transaction reverted for an unrecognized reason

### ISSUE THREAD

**Issue by NIC619** [nomiclabs/hardhat#1026]
```
Error: Transaction reverted for an unrecognized reason. Please report this to help us improve Hardhat.
      at TransparentUpgradeableProxy._delegate (contracts/test.sol:84)
      at TransparentUpgradeableProxy._delegate (contracts/test.sol:84)
      at TransparentUpgradeableProxy._fallback (contracts/test.sol:109)
      at Reflecter.reflect (contracts/test.sol:53)
      at Shooter.shoot (contracts/test.sol:30)
      at TransparentUpgradeableProxy._delegate (contracts/test.sol:84)
      at TransparentUpgradeableProxy._fallback (contracts/test.sol:109)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1282:9)
      at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:101:14)
      at EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/ethers-provider-wrapper.ts:13:20)
```

The error takes place when
- 1. [upgradeable proxy](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/UpgradeableProxy.soll) is used and
- 2. during the message call to external contract, the external contract `transfer` ether to proxy contract

The underlying problem is actually `OutOfGas` error since `transfer` only provides limited amount of gas for the callee and the gas is just not enough for proxy to further delegate the call. If `transfer` is changed to `.call{value: …}("")` it will work.

**Comment by fvictorio** [comment]
Hi @NIC619. Sorry for not responding before. I'm cleaning up old issues so I'm going to close this one. We've improved our error detection code a lot since this was submitted, so it's hard to know if it's still an issue, but please re-open if it is!
