### ISSUE TITLE
AST parsing for Hardhat Network fails sometimes

### ISSUE THREAD

**Issue by scnale** [nomiclabs/hardhat#1056]
We know that in Hardhat 2.0.2 the AST parser of the Hardhat Network may fail when attempting to produce a function selector.
From what I've seen, `FunctionDefinition` nodes are parsed without accounting for their `visibility`.
If the `visibility` is not `public` or `external` there's no need to attempt the derivation of a function selector. Note that this may be what is causing some of these failures because additional types may be used in internal functions versus public functions. See the [relevant source line](https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/internal/hardhat-network/stack-traces/compiler-to-model.ts#L180).

That said, we still don't have a case where we can reproduce this failure.

**Comment by poegva** [comment]
I am having the same issue after adding this contract to my project: https://pastebin.com/vffXdnYu

The issue was with the line  `mapping(IERC20 => bool) public poolExistence;`

After replacing it to ` mapping(address => bool) public poolExistence;` problem disappeared

**Comment by fvictorio** [comment]
@poegva I think this is fixed in the latest version of hardhat. Please let us know if that's not the case.

**Comment by BuggerBag** [comment]
Hi, I have similar problem with my contract
```D:\benchmark\driver>npx hardhat test --verbose
  hardhat:core:config Loading Hardhat config from D:\benchmark\driver\hardhat.config.js +0ms
  hardhat:core:global-dir Looking up Client Id at C:\Users\cloud\AppData\Local\hardhat-nodejs\Data\analytics.json +0ms
  hardhat:core:global-dir Client Id found: 9cac281e-1178-4c9f-b6d8-1e274be78e22 +1ms
  hardhat:core:analytics Sending hit for /task/builtin +0ms
  hardhat:core:analytics Hit payload: {"v":"1","t":"pageview","tid":"UA-117668706-3","cid":"9cac281e-1178-4c9f-b6d8-1e274be78e22","dp":"/task/builtin","dh":"cli.hardhat.org","ua":"Node/v16.13.2 (Windows NT 6.1; Win64; x64)","cs":"Developer","cm":"User Type","cd1":"hardhat-project","cd2":"Developer","cd3":"Hardhat 2.6.8"} +2ms
  hardhat:core:hre Creating HardhatRuntimeEnvironment +0ms
  hardhat:core:hre Running task test +253ms
  hardhat:core:hre Running task compile +1ms
  hardhat:core:hre Running task compile:get-compilation-tasks +1ms
  hardhat:core:hre Running task compile:solidity +1ms
  hardhat:core:hre Running task compile:solidity:get-source-paths +0ms
  hardhat:core:hre Running task compile:solidity:get-source-names +25ms
  hardhat:core:hre Running task compile:solidity:get-dependency-graph +16ms
  hardhat:core:hre Running task compile:solidity:read-file +2ms
  hardhat:core:hre Running task compile:solidity:read-file +8ms
  hardhat:core:hre Running task compile:solidity:get-compilation-jobs +24ms
  hardhat:core:tasks:compile The dependency graph was divided in '1' connected components +0ms
  hardhat:core:hre Running task compile:solidity:get-compilation-job-for-file +3ms
  hardhat:core:compilation-job File 'D:\benchmark\driver\contracts\EtherStore.sol' will be compiled with version '0.8.10' +0ms
  hardhat:core:compilation-job File 'D:\benchmark\driver\node_modules\hardhat\console.sol' added as dependency of 'D:\benchmark\driver\contracts\EtherStore.sol' +3ms
  hardhat:core:hre Running task compile:solidity:get-compilation-job-for-file +35ms
  hardhat:core:compilation-job File 'D:\benchmark\driver\node_modules\hardhat\console.sol' will be compiled with version '0.8.10' +2ms
  hardhat:core:hre Running task compile:solidity:handle-compilation-jobs-failures +2ms
  hardhat:core:hre Running task compile:solidity:filter-compilation-jobs +1ms
  hardhat:core:tasks:compile '2' jobs were filtered out +45ms
  hardhat:core:hre Running task compile:solidity:merge-compilation-jobs +6ms
  hardhat:core:hre Running task compile:solidity:compile-jobs +1ms
  hardhat:core:tasks:compile No compilation jobs to compile +1ms
  hardhat:core:hre Running task compile:solidity:log:nothing-to-compile +0ms
  hardhat:core:hre Running task compile:solidity:log:compilation-result +60ms
  hardhat:core:hre Running task test:get-test-files +3ms
  hardhat:core:hre Running task test:setup-test-environment +1ms
  hardhat:core:hre Running task test:show-fork-recommendations +1ms
  hardhat:core:hre Running task test:run-mocha-tests +1ms


  hardhat:core:hre Creating provider for network hardhat +655ms
  hardhat:core:analytics Hit for "/task/builtin" sent successfully +2s
The Hardhat Network tracing engine could not be initialized. Run Hardhat with --verbose to learn more.
  hardhat:core:hardhat-network:node Hardhat Network tracing disabled: ContractsIdentifier failed to be initialized. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  TypeError: Cannot read properties of undefined (reading 'content')
    at createSourcesModelFromAst (D:\benchmark\driver\node_modules\hardhat\src\internal\hardhat-network\stack-traces\compiler-to-model.ts:67:41)
    at Object.createModelsAndDecodeBytecodes (D:\benchmark\driver\node_modules\hardhat\src\internal\hardhat-network\stack-traces\compiler-to-model.ts:37:3)
    at new HardhatNode (D:\benchmark\driver\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:348:27)
    at Function.create (D:\benchmark\driver\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:237:18)
    at HardhatNetworkProvider._init (D:\benchmark\driver\node_modules\hardhat\src\internal\hardhat-network\provider\provider.ts:240:28)
    at HardhatNetworkProvider._send (D:\benchmark\driver\node_modules\hardhat\src\internal\hardhat-network\provider\provider.ts:184:5)
    at HardhatNetworkProvider.request (D:\benchmark\driver\node_modules\hardhat\src\internal\hardhat-network\provider\provider.ts:110:18)
    at WaffleMockProviderAdapter.send (D:\benchmark\driver\node_modules\@nomiclabs\hardhat-waffle\src\waffle-provider-adapter.ts:31:20) +0ms```
