### ISSUE TITLE
Hardhat Network tracing engine could not be initialized

### ISSUE THREAD

**Issue by StillFantastic** [nomiclabs/hardhat#1173]
When I run `npx hardhat test --verbose`, there is an error message:
> The Hardhat Network tracing engine could not be initialized. Run Hardhat with --verbose to learn more.
  hardhat:core:hardhat-network:node Hardhat Network tracing disabled: ContractsIdentifier failed to be initialized. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  TypeError: Cannot read property 'startsWith' of undefined
    at toCanonicalAbiType (/Users/billhsu/Desktop/work/github/test-hardhat/node_modules/hardhat/src/internal/hardhat-network/stack-traces/compiler-to-model.ts:490:12)
    at astFunctionDefinitionToSelector (/Users/billhsu/Desktop/work/github/test-hardhat/node_modules/hardhat/src/internal/hardhat-network/stack-traces/compiler-to-model.ts:467:21)
    at processFunctionDefinitionAstNode (/Users/billhsu/Desktop/work/github/test-hardhat/node_modules/hardhat/src/internal/hardhat-network/stack-traces/compiler-to-model.ts:180:9)
    at processContractAstNode (/Users/billhsu/Desktop/work/github/test-hardhat/node_modules/hardhat/src/internal/hardhat-network/stack-traces/compiler-to-model.ts:127:7)
    at createSourcesModelFromAst (/Users/billhsu/Desktop/work/github/test-hardhat/node_modules/hardhat/src/internal/hardhat-network/stack-traces/compiler-to-model.ts:81:7)
    at Object.createModelsAndDecodeBytecodes (/Users/billhsu/Desktop/work/github/test-hardhat/node_modules/hardhat/src/internal/hardhat-network/stack-traces/compiler-to-model.ts:33:3)
    at new HardhatNode (/Users/billhsu/Desktop/work/github/test-hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:206:27)
    at Function.create (/Users/billhsu/Desktop/work/github/test-hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:145:18) +0ms
  hardhat:core:cli Killing Hardhat after successfully running task test +0ms

And I'm using node v11.0.0, to reproduce:
1. Clone https://github.com/StillFantastic/test-hardhat
2. npm install
3. npx hardhat test

Not sure why that piece of solidity code cause the error.

**Comment by scnale** [comment]
Thanks a lot for reporting this @StillFantastic! I think this is what we were seeing on #1056. We'll take a look at it as soon as we can.

**Comment by bhargav55** [comment]
This issue still persists when using solidity version 0.8.x
