### ISSUE TITLE
HH502: type error resulting in "couldn't obtain solc version list"

### ISSUE THREAD

**Issue by Shirikatsu** [nomiclabs/hardhat#1174]
Using macOS 10.15.6. I hope this has nothing to do with operating system or this problem would be a massive joke. My colleague does not have any issues of the kind running Ubuntu. Currently this blocks me from doing anything. I will migrate back to Truffle if this isn't solved/solveable.

Using `devDependencies`:

``` json
"@nomiclabs/hardhat-truffle5": "^2.0.0",
"@nomiclabs/hardhat-web3": "^2.0.0",
"hardhat": "^2.0.7",
```

With a config file:

```javascript
/**
 * @type import('hardhat/config').HardhatUserConfig
 */

require("@nomiclabs/hardhat-truffle5");
require("@nomiclabs/hardhat-web3");
require("solidity-coverage")

module.exports = {

  defaultNetwork: "hardhat",
  networks: {
    hardhat:{
      gas:"auto" //gas limit is set dynamically,
    },
    development: {
     url: "http://localhost:8545",             
     network_id: "*",     
    },
    soliditycoverage: {
      url: "http://localhost:8545",             
      network_id: "*",  
    }
  },

  // Configure your compilers
  solidity: {
    version: "0.6.2",    
    settings: {
      optimizer: {
        enabled: true,
        runs: 100
      }
    }
  },
  plugins: ["solidity-coverage"]
};
```

Attempting to compile contracts with `npx hardhat compile --show-stack-traces` results in:

```bash
Error HH502: Couldn't download compiler versions list. Please check your connection.

{ HardhatError: HH502: Couldn't download compiler versions list. Please check your connection.
    at CompilerDownloader.downloadCompilersList (/Users/Shirikatsu/git/project/node_modules/hardhat/src/internal/solidity/compiler/downloader.ts:185:13)
    at <anonymous>
  parent: TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function
    at Object.promisify (internal/util.js:215:11)
    at download (/Users/Shirikatsu/git/project/node_modules/hardhat/src/internal/util/download.ts:13:31)
    at <anonymous>,
  name: 'HardhatError',
  errorDescriptor: 
   { number: 502,
     message: 'Couldn\'t download compiler versions list. Please check your connection.',
     title: 'Couldn\'t obtain `solc` version list',
     description: 'Couldn\'t download `solc`\'s version list. \n      \nPlease check your Internet connection.',
     shouldBeReported: false },
  number: 502,
  messageArguments: {},
  _isHardhatError: true }
```

My internet connection is fine, hence you being able to read this issue. The error message is clearly incorrect and defaulting to this message due to unexpected errors. Please advise/fix.

**Comment by fvictorio** [comment]
Hi @Shirikatsu. Are you still having this issue? A lot of Hardhat's users (and part of our team) are on mac, so the OS shouldn't be the problem.

I agree that the error is misleading if the problem isn't your connection.

**Comment by Shirikatsu** [comment]
Thanks for getting back. Not not having this issue anymore. It turned out to be a mismatched version of node causing this issue.

**Comment by vyorkin** [comment]
Got the same error on NixOS, node v15.11.0, related: #1246
