### ISSUE TITLE
could not generate stacktrace. please report

### ISSUE THREAD

**Issue by sirpy** [nomiclabs/hardhat#1185]
I have the following function
```
function bountyFor(address _invitee) public isActive {
		require(
			canCollectBountyFor(_invitee),
			"user not elligble for bounty yet"
		);
                .....
}
function canCollectBountyFor(address invitee) public view returns (bool);
```
when testing this function with .to.revertedWith hardhat complains at the end about not able to produce stack traces.
I did a quick test with replacing the call to `canCollectBountyFor(_invitee)` with `false` and it stopped complaining.
so my guess it has to do with internal calls

**Comment by UncleGrandpa925** [comment]
I have the same issue too. Here are my output when I use --verbose option: 
`
hardhat:core:hardhat-network:node Could not generate stack trace. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  Error: This shouldn't happen: a call trace has no functionJumpdest but has already jumped into a function
    at SolidityTracer._getEntryBeforeFailureInModifier (/Users/unclegrandpa/Documents/Projects/Pendle/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:1084:13)
    at SolidityTracer._rawTraceEvmExecution (/Users/unclegrandpa/Documents/Projects/Pendle/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:330:20)
    at SolidityTracer._traceEvmExecution (/Users/unclegrandpa/Documents/Projects/Pendle/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:236:29)
    at SolidityTracer._getCallMessageStackTrace (/Users/unclegrandpa/Documents/Projects/Pendle/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:147:17)
    at SolidityTracer.getStackTrace (/Users/unclegrandpa/Documents/Projects/Pendle/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:74:19)
    at SolidityTracer._rawTraceEvmExecution (/Users/unclegrandpa/Documents/Projects/Pendle/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:396:35)
    at SolidityTracer._traceEvmExecution (/Users/unclegrandpa/Documents/Projects/Pendle/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:236:29)
    at SolidityTracer._getCallMessageStackTrace (/Users/unclegrandpa/Documents/Projects/Pendle/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:147:17)
    at SolidityTracer.getStackTrace (/Users/unclegrandpa/Documents/Projects/Pendle/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:74:19)
    at HardhatNode._manageErrors (/Users/unclegrandpa/Documents/Projects/Pendle/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:913:41)
    at HardhatNode.runTransactionInNewBlock (/Users/unclegrandpa/Documents/Projects/Pendle/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:312:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at EthModule._sendTransactionAndReturnHash (/Users/unclegrandpa/Documents/Projects/Pendle/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1303:9)
    at HardhatNetworkProvider.request (/Users/unclegrandpa/Documents/Projects/Pendle/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:102:18)
    at WaffleMockProviderAdapter.send (/Users/unclegrandpa/Documents/Projects/Pendle/contracts/node_modules/@nomiclabs/hardhat-waffle/src/waffle-provider-adapter.ts:31:20) +543ms
`

**Comment by definim** [comment]
#metoo .

Hardhat network. Reproducible. The test is the following:
```
      it('myTest', async () => {
        await expect(myContract.connect(myAccount).myFunction(myUint256Param1, myBytes32Param)).to.be.revertedWith(
          `Some error message`,
        )
      })
```

And the verbose output is:
```
hardhat:core:hardhat-network:node Could not generate stack trace. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  Error: This shouldn't happen: a call trace has no functionJumpdest but has already jumped into a function
    at SolidityTracer._getEntryBeforeFailureInModifier (/Users/myUser/dev/defi/myRepo/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:1086:13)
    at SolidityTracer._rawTraceEvmExecution (/Users/myUser/dev/defi/myRepo/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:332:20)
    at SolidityTracer._traceEvmExecution (/Users/myUser/dev/defi/myRepo/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:238:29)
    at SolidityTracer._getCallMessageStackTrace (/Users/myUser/dev/defi/myRepo/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:149:17)
    at SolidityTracer.getStackTrace (/Users/myUser/dev/defi/myRepo/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:76:19)
    at SolidityTracer._getUnrecognizedMessageStackTrace (/Users/myUser/dev/defi/myRepo/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:177:44)
    at SolidityTracer.getStackTrace (/Users/myUser/dev/defi/myRepo/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:79:17)
    at HardhatNode._manageErrors (/Users/myUser/dev/defi/myRepo/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1152:41)
    at HardhatNode._gatherTraces (/Users/myUser/dev/defi/myRepo/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:935:30)
    at HardhatNode._mineBlockWithPendingTxs (/Users/myUser/dev/defi/myRepo/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1003:21) +0ms
```

**Comment by chanhosuh** [comment]
I had the same issue... changing the name of a public function within my contract (a different one than the one being tested for revert) fixed the issue.  The problem arose when I renamed a function, so I wondered whether it was that... a pretty weird result for something so innocuous.

**Comment by paulrberg** [comment]
This could be a bug in the Solidity compiler. I posted my findings in https://github.com/ethereum/solidity/issues/11898.

**Comment by paulrberg** [comment]
Yep, as per this [explanation](https://github.com/ethereum/solidity/issues/11898#issuecomment-914288597), this was indeed a bug in Solidity. v0.8.8 should have it patched.

**Comment by fvictorio** [comment]
That's great @paulrberg, thanks for letting us know.

I'm going to tentatively close this then.

**Comment by paulrberg** [comment]
[Solidity v0.8.8](https://github.com/ethereum/solidity/releases/tag/v0.8.8) just dropped today. I upgraded to it and that made the "Could not generate stacktrace" error go away.

Everyone in this thread should upgrade to v0.8.8 as soon as possible.
