### ISSUE TITLE
Unrecognized deployment failure due to gas limit.

### ISSUE THREAD

**Issue by bh2smith** [nomiclabs/hardhat#1218]
My command line told me to report this issue to help improve hardhat, so here is the story:

While running hardhat deployment with a fixed gas limit (lower than necessary to succeed) we found the following error message:

```
Error: ERROR processing /gnosis/gp-v2-contracts/src/deploy/002_settlement.ts:
Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.
    at <UnrecognizedContract>.<unknown> (unknown)
    at <UnrecognizedContract>.<unknown> (0x4e59b44847b379578588920ca78fbf26c0b4956c)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at EthModule._sendTransactionAndReturnHash (/gnosis/gp-v2-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1303:9)
    at HardhatNetworkProvider.request (/gnosis/gp-v2-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:102:18)
    at _deploy (/gnosis/gp-v2-contracts/node_modules/hardhat-deploy/src/helpers.ts:389:14)
    at _deployOne (/gnosis/gp-v2-contracts/node_modules/hardhat-deploy/src/helpers.ts:647:18)
    at Object.deploySettlement [as func] (/gnosis/gp-v2-contracts/src/deploy/002_settlement.ts:16:3)
    at DeploymentsManager.executeDeployScripts (/gnosis/gp-v2-contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:988:22)
    at DeploymentsManager.executeDeployScripts (/gnosis/gp-v2-contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:991:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at DeploymentsManager.runDeploy (/gnosis/gp-v2-contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:819:5)
    at Environment._runTaskDefinition (/gnosis/gp-v2-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/gnosis/gp-v2-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:130:14)
    at SimpleTaskDefinition.action (/gnosis/gp-v2-contracts/node_modules/hardhat-deploy/src/index.ts:405:32)
    at Environment._runTaskDefinition (/gnosis/gp-v2-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/gnosis/gp-v2-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:130:14)
    at SimpleTaskDefinition.action (/gnosis/gp-v2-contracts/node_modules/hardhat-deploy/src/index.ts:470:5)
    at Environment._runTaskDefinition (/gnosis/gp-v2-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
error Command failed with exit code 1.
```

Turned out that simply increasing the fixed `gasLimit` was all that was necessary to pass.

## Reproduce this error by

Check out this [PR](https://github.com/gnosis/gp-v2-contracts/pull/396) (introducing larger contract bytecode and increasing the gas limit in migration script). Simply revert the `gasLimit` back to `3e5` there and `yarn deploy` will result in the above error.

**Comment by fvictorio** [comment]
Closing this since we seem to have a nice error now (though I don't know when we introduced it):

```
Transaction requires at least 56540 gas but got 10
```

Please re-open if you think this is still valid!
