### ISSUE TITLE
[hardhat-etherscan] Error in plugin @nomiclabs/hardhat-etherscan: The constructor has .. parameters but 0 arguments were provided instead.

### ISSUE THREAD

**Issue by krasi-georgiev** [nomiclabs/hardhat#1245]
```
Error in plugin @nomiclabs/hardhat-etherscan: The constructor for contracts/Lens.sol:Lens has 2 parameters
but 0 arguments were provided instead.
```
https://github.com/tellor-io/lens/blob/4b115af4b3384bd6bbf17f8d562042a6394aac0f/hardhat.config.js#L38

I know that both of these args are provided and a `console.log(masterAddress, dataIDs)` proves that are not empty

That was working before I did some refactoring of the solidity code and before I upgraded to .0.7 solidity
I think it might be something to do with the fact that the constructor argument is an array of structs
otherwise the tests pass with no problem and it deploys fine on rinkeby

**Comment by krasi-georgiev** [comment]
I just tried it on a completely fresh project with 0.5 and 0.6 pragma and still the same so seems like a bug.

**Comment by krasi-georgiev** [comment]
full logs
```
 error occurred:

Error: missing argument:  in Contract constructor (count=0, expectedCount=2, code=MISSING_ARGUMENT, version=contracts/5.0.11)
    at Logger.makeError (/home/krasi/src/github.com/tellor-io/lens/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (/home/krasi/src/github.com/tellor-io/lens/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at Logger.checkArgumentCount (/home/krasi/src/github.com/tellor-io/lens/node_modules/@ethersproject/logger/src.ts/index.ts:276:18)
    at ContractFactory.<anonymous> (/home/krasi/src/github.com/tellor-io/lens/node_modules/@ethersproject/contracts/src.ts/index.ts:1163:16)
    at step (/home/krasi/src/github.com/tellor-io/lens/node_modules/@ethersproject/contracts/lib/index.js:46:23)
    at Object.next (/home/krasi/src/github.com/tellor-io/lens/node_modules/@ethersproject/contracts/lib/index.js:27:53)
    at /home/krasi/src/github.com/tellor-io/lens/node_modules/@ethersproject/contracts/lib/index.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/home/krasi/src/github.com/tellor-io/lens/node_modules/@ethersproject/contracts/lib/index.js:17:12)
    at ContractFactory.deploy (/home/krasi/src/github.com/tellor-io/lens/node_modules/@ethersproject/contracts/lib/index.js:1071:16) {
  reason: 'missing argument:  in Contract constructor',
  code: 'MISSING_ARGUMENT',
  count: 0,
  expectedCount: 2
}
npm ERR! code 1
npm ERR! path /home/krasi/src/github.com/tellor-io/lens
npm ERR! command failed
npm ERR! command sh -c hardhat "deploy" "--network" "rinkeby" "--oracle-address" "0xfe41cb708cd98c5b20423433309e55b53f79134a"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/krasi/.npm/_logs/2021-02-15T20_47_56_740Z-debug.log
```

**Comment by krasi-georgiev** [comment]
the fix was to use task `verify:verify` , not sure why it works with just `verify` before
