### ISSUE TITLE
Error HH502: Couldn't download compiler versions list. Please check your connection.

### ISSUE THREAD

**Issue by talbaneth** [nomiclabs/hardhat#1246]
when running "npx hardhat --show-stack-traces compile" on v2.0.10 I get:

Error HH502: Couldn't download compiler versions list. Please check your connection.

{ HardhatError: HH502: Couldn't download compiler versions list. Please check your connection.
    at CompilerDownloader.downloadCompilersList (/home/talbaneth/prycto/liquidation/mcd/node_modules/hardhat/src/internal/solidity/compiler/downloader.ts:185:13)
    at <anonymous>
  parent: TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function
    at Object.promisify (internal/util.js:209:11)
    at download (/home/talbaneth/prycto/liquidation/mcd/node_modules/hardhat/src/internal/util/download.ts:13:31)
    at <anonymous>,
  name: 'HardhatError',
  errorDescriptor: 
   { number: 502,
     message: 'Couldn\'t download compiler versions list. Please check your connection.',
     title: 'Couldn\'t obtain `solc` version list',
     description: 'Couldn\'t download `solc`\'s version list. \n      \nPlease check your Internet connection.',
     shouldBeReported: false },
  number: 502,
  messageArguments: {},
  _isHardhatError: true }

**Comment by alcuadrado** [comment]
Thanks for opening this issue. Can you provide more info about the environment you are running Hardhat on? OS? Version? Node version? npm/yarn? version?

**Comment by talbaneth** [comment]
unbuntu16.04
hardhat v2.0.10
node v9.4.0
npm 5.6.0

**Comment by fvictorio** [comment]
Hardhat requires node >=10. Maybe we should just stop and print an error when node <10 is used.

**Comment by talbaneth** [comment]
Got it, I upgraded node and it seem to solve the problem. Thanks!

**Comment by vyorkin** [comment]
Got the same error, NixOS, node v15.11.0

**Comment by Hodey** [comment]
Hardhat version 2.6.8
solidity 0.8.1
node v14.16.1
npm 6.14.12
macOs Catalina 10.15.7
------------------
pass the compile 😋.

**Comment by sugalivijaychari** [comment]
I got the issue.
Hardhat version 2.8.4,
node v16.13.0,
npm 8.1.0,
OS Red Hat Enterprise Linux Server release 7.9 (Maipo),
FYI, I am running this behind firewall. 
I thought hardhat might solve the same compiler download problem existed for truffle.
But I still see the same problem in hardhat.
Unable to download compiler versions.
How can I manually download compiler versions if I am getting the below error for the command `npx hardhat compile`.

`Error HH502: Couldn't download compiler versions list. Please check your connection.

HardhatError: HH502: Couldn't download compiler versions list. Please check your connection.
    at CompilerDownloader.downloadCompilersList (/Quartz_New/NFT/Vijay/Explore/hardhatdevelopment/node_modules/hardhat/src/internal/solidity/compiler/downloader.ts:201:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CompilerDownloader.getCompilersList (/Quartz_New/NFT/Vijay/Explore/hardhatdevelopment/node_modules/hardhat/src/internal/solidity/compiler/downloader.ts:162:7)
    at CompilerDownloader._fetchVersionPath (/Quartz_New/NFT/Vijay/Explore/hardhatdevelopment/node_modules/hardhat/src/internal/solidity/compiler/downloader.ts:256:16)
    at CompilerDownloader._versionExists (/Quartz_New/NFT/Vijay/Explore/hardhatdevelopment/node_modules/hardhat/src/internal/solidity/compiler/downloader.ts:274:25)
    at CompilerDownloader.getCompilerBuild (/Quartz_New/NFT/Vijay/Explore/hardhatdevelopment/node_modules/hardhat/src/internal/solidity/compiler/downloader.ts:183:9)
    at CompilerDownloader.isCompilerDownloaded (/Quartz_New/NFT/Vijay/Explore/hardhatdevelopment/node_modules/hardhat/src/internal/solidity/compiler/downloader.ts:74:27)
    at SimpleTaskDefinition.action (/Quartz_New/NFT/Vijay/Explore/hardhatdevelopment/node_modules/hardhat/src/builtin-tasks/compile.ts:492:36)
    at Environment._runTaskDefinition (/Quartz_New/NFT/Vijay/Explore/hardhatdevelopment/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Quartz_New/NFT/Vijay/Explore/hardhatdevelopment/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)

    Caused by: FetchError: request to https://binaries.soliditylang.org/linux-amd64/list.json failed, reason: getaddrinfo ENOTFOUND binaries.soliditylang.org
        at ClientRequest.<anonymous> (/Quartz_New/NFT/Vijay/Explore/hardhatdevelopment/node_modules/node-fetch/lib/index.js:1491:11)
        at ClientRequest.emit (node:events:390:28)
        at TLSSocket.socketErrorListener (node:_http_client:447:9)
        at TLSSocket.emit (node:events:390:28)
        at emitErrorNT (node:internal/streams/destroy:157:8)
        at emitErrorCloseNT (node:internal/streams/destroy:122:3)
        at processTicksAndRejections (node:internal/process/task_queues:83:21)`

**Comment by alcuadrado** [comment]
Maybe you need to use a proxy

**Comment by sugalivijaychari** [comment]
@alcuadrado , yes I used proxy and it worked. Thanks. I used below commands:
`set HTTP_PROXY=<username>:<password>@<ip_address>:<ip_port>`
`set HTTPS_PROXY=<username>:<password>@<ip_address>:<ip_port>`

**Comment by AbuSantos** [comment]
So if anyone having this problem on a windows, just put the solidity object above the hh default network o  the hardhat config file

**Comment by AryanSai** [comment]
> @alcuadrado , yes I used proxy and it worked. Thanks. I used below commands: `export HTTP_PROXY=<username>:<password>@<ip_address>:<ip_port>` `export HTTPS_PROXY=<username>:<password>@<ip_address>:<ip_port>`

Where should I add this?

**Comment by fvictorio** [comment]
@AryanSai those are commands to add environment variables to your current session (read [this](https://unix.stackexchange.com/questions/3507/difference-between-shell-variables-which-are-exported-and-those-which-are-not-in) for an explanation).

**Comment by AryanSai** [comment]
OK thank you!!

**Comment by daniyaniazi** [comment]
What is http proxy address , username , password , port ?
