### ISSUE TITLE
Transaction reverted and Hardhat couldn't infer the reason: static call to non-static function

### ISSUE THREAD

**Issue by josojo** [nomiclabs/hardhat#1252]
Hi,

I got the following error:

```
AssertionError: Expected transaction to be reverted with function call to a non-contract account, but other exception was thrown: Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.
```
I am reporting it, as you guys might want to improve it. No worries, I will not bother you with fixing it quickly, as it is a minor issue...

This happens, if I am using a static contract call from one contract into another contract, but the other contract is actually trying to modify code:

I used the following interface with the VIEW function:
```
///
/// @dev Standardized interface for an allowList manager for easyAuction
/// The interface was inspired by EIP-1271
interface AllowListVerifier {
    /// @dev Should return whether the a specific user has access to an auction
    /// by returning the magic value from AllowListVerifierHelper
    function isAllowed(
        address user,
        uint256 auctionId,
        bytes calldata callData
    ) external view returns (bytes4);
}
```

But called the following contract that does not follow the interface:
```
contract StateChangingAllowListVerifier {
    bytes32 public test = bytes32(0);

    function isAllowed(
        address user,
        uint256 auctionId,
        bytes calldata callData
    ) external returns (bytes4) {
        test = keccak256(abi.encode(user, auctionId, callData));
    }
}
```

I was only doing that for test purposes, in order to make sure that the tx failed.

**Comment by fedgiac** [comment]
In case it helps, here is a minimal working example.

Solidity:
```
interface UnchangedState {
    function test() external view;
}

contract ChangingState {
    uint256 state = 0;

    function test() external /* not view */
    {
        state += 1;
    }
}

contract ExpectUnchangedState {
    function callTest(UnchangedState c) public {
        c.test();
    }
}
```

Test:
```
it("reverts", async () => {
  const ChangingState = await ethers.getContractFactory("ChangingState");
  const changingState = await ChangingState.deploy();
  const ExpectUnchangedState = await ethers.getContractFactory("ExpectUnchangedState");
  const expectUnchangedState = await ExpectUnchangedState.deploy();

  await expectUnchangedState.callTest(changingState.address);
});
```

Output of `hardhat test`:
```
1) reverts

  0 passing (1s)
  1 failing

  1) reverts:
     Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.
```

**Comment by CodeSandwich** [comment]
Looks very similar to https://github.com/nomiclabs/hardhat/issues/1227

**Comment by jamesmorgan** [comment]
Yep also seeing this alot - hoping for a fix 🙏🏻

**Comment by fvictorio** [comment]
Hi everyone. Hardhat [2.4.0](https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.4.0) comes with an improved error detection mechanism that should fix problems like these. I'm going to tentatively close this issue, but please re-open if you are still getting the same results.

**Comment by fedgiac** [comment]
Thanks for keeping us up to date! Unfortunately it doesn't look like this specific issue has been solver:

```
$ npx hardhat --version
2.4.0
$ npx hardhat test


  Test
    1) reverts


  0 passing (841ms)
  1 failing

  1) Test
       reverts:
     Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.
      at ChangingState.test (contracts/Test.sol:10)
      at ExpectUnchangedState.callTest (contracts/Test.sol:16)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at runNextTicks (internal/process/task_queues.js:64:3)
      at listOnTimeout (internal/timers.js:524:9)
      at processTimers (internal/timers.js:498:7)
      at HardhatNode._mineBlockWithPendingTxs (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1261:23)
      at HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:384:16)
      at EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1379:18)
```

I used the same configuration as the sample project from `hardhat init` and the code from my previous message.

**Comment by fvictorio** [comment]
@fedgiac I think that's kind of the same issue as [this one](https://github.com/nomiclabs/hardhat/issues/1320). You are not using a proxy, but the idea is the same: we should detect somehow that a write was done during a static call.

**Comment by jamiehewitt15** [comment]
Getting the same error `Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.` while using hardhat `2.7.0` would be great to get a more specific error message
