### ISSUE TITLE
Timeout after around 30 seconds when connecting to WebSocket

### ISSUE THREAD

**Issue by dievardump** [nomiclabs/hardhat#1254]
## environment

OS: Ubuntu 20.04.2 LTS
node: 14.15.4
npm: 7.5.4
web3: 1.3.2
hardhat: 2.0.10

## description

I can't really test my dApp too much because I get disconnected after approximately 30 seconds when connecting to the node using web3.js

Process:
run `npx hardhat node` (output is ok; listens on 8545, lists the address)
Then I launch my dApp which connects an instance of web3 with: `new Web3(new Web3.providers.WebsocketProvider('ws://localhost:8545'))`
I subscribe to some logs
I do interact with my contract and get the logs outputs in the subscribe
Then I stop interacting with the chain and the dApp backend after around 30 seconds throws:

```
(node:117088) UnhandledPromiseRejectionWarning: Error: Maximum number of reconnect attempts reached!
    at Object.MaxAttemptsReachedOnReconnectingError (/var/www/html/blockchain/beyondNFT/api/node_modules/web3-core-helpers/lib/errors.js:60:16)
    at /var/www/html/blockchain/beyondNFT/api/node_modules/web3-providers-ws/lib/index.js:350:37
    at Map.forEach (<anonymous>)
    at WebsocketProvider.reconnect (/var/www/html/blockchain/beyondNFT/api/node_modules/web3-providers-ws/lib/index.js:349:27)
    at WebsocketProvider._onClose (/var/www/html/blockchain/beyondNFT/api/node_modules/web3-providers-ws/lib/index.js:149:14)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/var/www/html/blockchain/beyondNFT/api/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (/var/www/html/blockchain/beyondNFT/api/node_modules/websocket/lib/W3CWebSocket.js:219:14)
    at WebSocketClient.<anonymous> (/var/www/html/blockchain/beyondNFT/api/node_modules/websocket/lib/W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:315:20)
    at WebSocketClient.failHandshake (/var/www/html/blockchain/beyondNFT/api/node_modules/websocket/lib/WebSocketClient.js:339:10)
    at ClientRequest.<anonymous> (/var/www/html/blockchain/beyondNFT/api/node_modules/websocket/lib/WebSocketClient.js:278:18)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at Socket.socketOnData (_http_client.js:509:22)
    at Socket.emit (events.js:315:20)
```

**Comment by dievardump** [comment]
The error was not linked to Hardhat but to my own code, sorry about this.
