### ISSUE TITLE
mainnet forking with OpenEthereum fails with `blockTag` errors

### ISSUE THREAD

**Issue by KillerByte** [nomiclabs/hardhat#1257]
I am attempting to use a synced local node of OpenEthereum as a JSONRPC target for mainnet forking. However, I am getting a variety of errors having to do with `invalid blockTag`.

For example, if I attempt to use `signer.getBalance()` from ethers while using mainnet forking, it returns this error:

```
InvalidInputError: Received invalid block tag 717651011697952300806243805620595611188106730737. Latest block number is 11878892
      at EthModule._blockTagToBlockNumber (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1072:13)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at runNextTicks (internal/process/task_queues.js:66:3)
      at listOnTimeout (internal/timers.js:523:9)
      at processTimers (internal/timers.js:497:7)
      at EthModule._getBalanceAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:434:25)
      at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:102:18)
      at EthersProviderWrapper.send (node_modules/hardhat-deploy-ethers/src/ethers-provider-wrapper.ts:13:20)
```

When making a ethers contract call (read only), there is another error:

```
Error: invalid blockTag
      at Formatter.blockTag (node_modules/@ethersproject/providers/src.ts/formatter.ts:236:15)
      at EthersProviderWrapper.<anonymous> (node_modules/@ethersproject/providers/src.ts/base-provider.ts:1381:31)
      at step (node_modules/@ethersproject/providers/lib/base-provider.js:46:23)
      at Object.next (node_modules/@ethersproject/providers/lib/base-provider.js:27:53)
      at fulfilled (node_modules/@ethersproject/providers/lib/base-provider.js:18:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Here is the configuration in use for hardhat network:

```
{
  networks: {
    hardhat: {
      chainId: 1337,
      accounts: {
        mnemonic: '...'
      },
      forking: {
        url: 'http://my.eth.node:8545',
      }
    },
  },
```

OpenEthereum is not in "archival" mode, but I am not trying to pin to a historical block.

Expected behavior is not to be getting these errors... I really wish I knew what was going on.

**Comment by KillerByte** [comment]
OpenEthereum is "full" node, not light
OpenEthereum v3.0.1

**Comment by KillerByte** [comment]
turns out the error was in my code. the call to signer get balance I had confusingly added an extra argument, like:

```
signer.getBalance(addressOfSigner)
```

this caused hardhat to interpret the argument as a `blockTag`. It parsed the address hex into a big number, and then tried to load with blocktag. This error somehow propagated to other functions as well, which is why I got so confused.

Ideally, hardhat would have not just converted the address into a number and rolled into an error like this, but that can be a separate issue if the team wants it.

**Comment by fvictorio** [comment]
> Ideally, hardhat would have not just converted the address into a number and rolled into an error like this, but that can be a separate issue if the team wants it.

That would be great, but:

1) I'm not sure if this should be hardhat's responsibility, sounds like an ethers thing.
2) Even then, I'm not sure if there's a way to tell apart between a genuine use of a hex and an address.

Anyway, you could try opening an issue on ethers, maybe there is a proper way to avoid this problem. And of course, if you think there's something we can do, please open an issue.

**Comment by fulldecent** [comment]
Here are solutions to the specific problem above

Generic:

```javascript
async function getBalance (account) {
  return new BN(await network.provider.send('eth_getBalance', [account]));
}

```

web3.js (e.g. you copy/pasted from OpenZeppelin Contracts)

```javascript
async function getBalance (account) {
  return new BN(await hardhat.web3.eth.getBalance(account));
}
```
