### ISSUE TITLE
Error [InitializationError]: First argument must be an abstract-leveldown compliant store.

### ISSUE THREAD

**Issue by InfernalHeir** [nomiclabs/hardhat#1285]
Hii Hardhat i am facing issue when i run the command `npx hardhat test`. i am getting an error attached below.

Error [InitializationError]: First argument must be an abstract-leveldown compliant store
    at new LevelUP (/home/bhupendra/bpool-contracts/node_modules/levelup/lib/levelup.js:45:13)
    at LevelUP (/home/bhupendra/bpool-contracts/node_modules/levelup/lib/levelup.js:29:12)
    at SecureTrie.Trie (/home/bhupendra/bpool-contracts/node_modules/merkle-patricia-tree/baseTrie.js:34:5)
    at SecureTrie.CheckpointTrie (/home/bhupendra/bpool-contracts/node_modules/merkle-patricia-tree/index.js:11:12)
    at new SecureTrie (/home/bhupendra/bpool-contracts/node_modules/merkle-patricia-tree/secure.js:14:18)
    at Object.makeStateTrie (/home/bhupendra/bpool-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/utils/makeStateTrie.ts:11:21)
    at Function.create (/home/bhupendra/bpool-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:126:31)
    at HardhatNetworkProvider._init (/home/bhupendra/bpool-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:275:46)
    at HardhatNetworkProvider._send (/home/bhupendra/bpool-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:221:5)
    at HardhatNetworkProvider.request (/home/bhupendra/bpool-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:102:18)
npm ERR! code 1
npm ERR! path /home/bhupendra/bpool-contracts
npm ERR! command failed
npm ERR! command sh -c hardhat "test"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bhupendra/.npm/_logs/2021-02-28T09_42_02_015Z-debug.log

hardhat-config.js
 require("@nomiclabs/hardhat-waffle");

// This is a sample Hardhat task. To learn how to create your own go to
// https://hardhat.org/guides/create-task.html
task("accounts", "Prints the list of accounts", async () => {
  const accounts = await ethers.getSigners();

  for (const account of accounts) {
    console.log(account.address);
  }
});

// You need to export an object to set up your config
// Go to https://hardhat.org/config/ to learn more

/**
 * @type import('hardhat/config').HardhatUserConfig
 */

module.exports = {
  defaultNetwork: "hardhat",
  networks: {
    hardhat: {}
  },
  solidity: {
    version: "0.6.12",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200
      }
    }
  },
  paths: {
    sources: "./contracts",
    tests: "./test",
    cache: "./cache",
    artifacts: "./artifacts"
  },
  mocha: {
    timeout: 20000
  }
};

**Comment by fvictorio** [comment]
Hi @InfernalHeir, are you still having this problem? If so, please use [our discord server](https://hardhat.org/discord) since this seems more of a question than a bug. Of course, please feel free to re-open if you think there's a bug on our side.
