### ISSUE TITLE
Error: network does not support ENS

### ISSUE THREAD

**Issue by stoplion** [nomiclabs/hardhat#1289]
`npx hardhat run --network localhost scripts/deploy.js`

Returns:

```Error: network does not support ENS (operation="ENS", network="unknown", code=UNSUPPORTED_OPERATION, version=providers/5.0.23)```

Stack trace:

```
 at Logger.makeError (/Users/georgenorris/Code/EthTextHH/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (/Users/georgenorris/Code/EthTextHH/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at EthersProviderWrapper.<anonymous> (/Users/georgenorris/Code/EthTextHH/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1397:20)
    at step (/Users/georgenorris/Code/EthTextHH/node_modules/@ethersproject/providers/lib/base-provider.js:46:23)
    at Object.next (/Users/georgenorris/Code/EthTextHH/node_modules/@ethersproject/providers/lib/base-provider.js:27:53)
    at fulfilled (/Users/georgenorris/Code/EthTextHH/node_modules/@ethersproject/providers/lib/base-provider.js:18:58)
```

**Comment by stoplion** [comment]
My mistake. Didn't pass deployer enough args

**Comment by samajammin** [comment]
Hey @stoplion - I'm hitting this same issue. Mind explaining how you solved? Thanks!

**Comment by alcuadrado** [comment]
It's normally an invalid address, or an object passed instead of an address. ethers get's confused and throws that

**Comment by nukec** [comment]
> It's normally an invalid address, or an object passed instead of an address. ethers get's confused and throws that

that was really an issue. for some random reason i was passing "1" into address param. great.

**Comment by xiaonengmiao** [comment]
> It's normally an invalid address, or an object passed instead of an address. ethers get's confused and throws that

Me TOO! Why we are doing all this lol

**Comment by mtajammulzia** [comment]
I am passing in correct address and it is still throwing me "network does not support ENS"
Using Kovan and Metamask. Can anyone help?

**Comment by LPerezDev** [comment]
> I am passing in correct address and it is still throwing me "network does not support ENS" Using Kovan and Metamask. Can anyone help?

I'm also stuck on this. Same scenario!

**Comment by Hachikoi-the-creator** [comment]
> It's normally an invalid address, or an object passed instead of an address. ethers get's confused and throws that

Left for a couple of weeks and now I'm copying two addresses lol

**Comment by xpanvictor** [comment]
Actually, check the type and the data you're trying to sign very well. Just resolved mine :)
