### ISSUE TITLE
Accessing blockhash for a block below 1 has a confusing error message

### ISSUE THREAD

**Issue by jtremback** [nomiclabs/hardhat#1385]
When I try to access the blockhash of a block height below one, it gives this error message:

Example solidity code:
```
blockhash(block.number - 200)
```

```
     ProviderError: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.
      at HttpProvider.request (node_modules/hardhat/src/internal/core/providers/http.ts:46:19)
      at GanacheGasMultiplierProvider.request (node_modules/hardhat/src/internal/core/providers/gas-providers.ts:170:34)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by alcuadrado** [comment]
Hey @jtremback, which version of Hardhat are you using? I can't get to reproduce this issue.

**Comment by fvictorio** [comment]
Closing this for now. Please re-open if you have a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) you can share.
