### ISSUE TITLE
unsupported eth_signTypedData

### ISSUE THREAD

**Issue by livingrock7** [nomiclabs/hardhat#1398]
Thank you for using Hardhat and taking the time to open an issue!

**Note that this issue tracker is not a support channel.**

- For help with Hardhat and Hardhat network, please use our [Discord server](https://hardhat.org/discord).
- For help with ethers.js, please go to [its Github Discussions](https://github.com/ethers-io/ethers.js/discussions).

If you are reporting a bug, please include reproduction steps. The best way to do this
is to include a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
If you can't do that, then include a link to your repo, and the steps to reproduce the problem. The easiest it
is to reproduce your problem, the faster we are going to be able to fix it.

https://github.com/bcnmy/mexa

Sudently started getting this error
MethodNotSupportedError: Method eth_signTypedData is not supported
      at EthModule.processRequest (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:244:15)
      at HardhatNetworkProvider._send (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:174:31)
      at processTicksAndRejections (internal/process/task_queues.js:88:5)
      at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:100:18)
      at EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
      at Context.<anonymous> (scripts/gas-usage/GasConsumption.js:611:25)

If you are submitting a feature request, please take the time to clearly describe your use case, and not only
your proposed solution.

**Comment by raymogg** [comment]
Providing a little more info on the above, I am getting the same issue in Hardhat@2.2.0, however downgrading to Hardhat@2.0.0 solves the issue and the `eth_signTypedData` call works.

**Comment by livingrock7** [comment]
Let me try Thanks @raymogg 
Although even if I just take ethersProvider in another project without hardhat and try this method does not work!

**Comment by fvictorio** [comment]
@livingrock7 which version of `ethers` and `hardhat-ethers` are you using? I belive ethers use the `eth_signTypedData_v4` method, that we still have, so this should work.
