### ISSUE TITLE
Command-line option --standard-json isn't supported for solc 4 before 0.4.11

### ISSUE THREAD

**Issue by jtakalai** [nomiclabs/hardhat#1480]
Repro:
- Create a new directory and cd there
- `npx hardhat`
- default answer (hit enter) to all fields
- change hardhat.config.js such that compiler version `"0.7.3"` becomes `"0.4.10"`
- modify Greeter.sol to the following:
```
//SPDX-License-Identifier: Unlicense
pragma solidity ^0.4.0;

contract Greeter {
  string greeting;

  function Greeter(string memory _greeting) public {
    greeting = _greeting;
  }

  function greet() public returns (string memory) {
    return greeting;
  }

  function setGreeting(string memory _greeting) public {
    greeting = _greeting;
  }
}
```
- `npx hardhat compile`

Expected:
```
  hardhat:core:config Loading Hardhat config from [REDACTED]/hardhat-epipe-repro/hardhat.config.js +0ms
[REDACTED]
  hardhat:core:hre Creating HardhatRuntimeEnvironment +0ms
  hardhat:core:hre Running task compile +99ms
  hardhat:core:hre Running task compile:get-compilation-tasks +1ms
  hardhat:core:hre Running task compile:solidity +0ms
  hardhat:core:hre Running task compile:solidity:get-source-paths +0ms
  hardhat:core:hre Running task compile:solidity:get-source-names +9ms
  hardhat:core:hre Running task compile:solidity:get-dependency-graph +3ms
  hardhat:core:hre Running task compile:solidity:read-file +1ms
  hardhat:core:hre Running task compile:solidity:get-compilation-jobs +95ms
  hardhat:core:tasks:compile The dependency graph was divided in '1' connected components +0ms
  hardhat:core:hre Running task compile:solidity:get-compilation-job-for-file +0ms
  hardhat:core:compilation-job File '[REDACTED]/hardhat-epipe-repro/contracts/Greeter.sol' will be compiled with version '0.4.11' +0ms
  hardhat:core:hre Running task compile:solidity:handle-compilation-jobs-failures +10ms
  hardhat:core:hre Running task compile:solidity:filter-compilation-jobs +0ms
  hardhat:core:tasks:compile '0' jobs were filtered out +11ms
  hardhat:core:hre Running task compile:solidity:merge-compilation-jobs +1ms
  hardhat:core:hre Running task compile:solidity:compile-jobs +0ms
  hardhat:core:tasks:compile Compiling 1 jobs +0ms
  hardhat:core:hre Running task compile:solidity:compile-job +0ms
  hardhat:core:tasks:compile Compiling job with version '0.4.11' +0ms
  hardhat:core:hre Running task compile:solidity:get-compiler-input +0ms
  hardhat:core:hre Running task compile:solidity:compile +1ms
  hardhat:core:hre Running task compile:solidity:solc:compile +0ms
  hardhat:core:hre Running task compile:solidity:solc:get-build +0ms
  hardhat:core:hre Running task compile:solidity:log:download-compiler-start +4ms
  hardhat:core:tasks:compile Checking native solc binary +29ms
  hardhat:core:hre Running task compile:solidity:log:download-compiler-end +91ms
  hardhat:core:hre Running task compile:solidity:log:run-compiler-start +0ms
Compiling 1 file with 0.4.11
  hardhat:core:hre Running task compile:solidity:solc:run +1ms
  hardhat:core:hre Running task compile:solidity:log:run-compiler-end +19ms
  hardhat:core:hre Running task compile:solidity:check-errors +0ms
  hardhat:core:hre Running task compile:solidity:log:compilation-errors +0ms
  hardhat:core:hre Running task compile:solidity:emit-artifacts +0ms
  hardhat:core:tasks:compile Emitting artifacts for file 'contracts/Greeter.sol' +89ms
  hardhat:core:tasks:compile Emitting artifact for contract 'Greeter' +0ms
  hardhat:core:hre Running task compile:solidity:get-artifact-from-compilation-output +2ms
  hardhat:core:artifacts Removing buildInfo '[REDACTED]/hardhat-epipe-repro/artifacts/build-info/4fcaafd3f46dcf11e57906a23462729a.json' +0ms
  hardhat:core:hre Running task compile:solidity:log:compilation-result +14ms
Compilation finished successfully
  hardhat:core:cli Killing Hardhat after successfully running task compile +0ms
```

- Actual:
```
  hardhat:core:config Loading Hardhat config from [REDACTED]/hardhat-epipe-repro/hardhat.config.js +0ms
[REDACTED]
  hardhat:core:hre Creating HardhatRuntimeEnvironment +0ms
  hardhat:core:hre Running task compile +98ms
  hardhat:core:hre Running task compile:get-compilation-tasks +0ms
  hardhat:core:hre Running task compile:solidity +0ms
  hardhat:core:hre Running task compile:solidity:get-source-paths +1ms
  hardhat:core:hre Running task compile:solidity:get-source-names +9ms
  hardhat:core:hre Running task compile:solidity:get-dependency-graph +3ms
  hardhat:core:hre Running task compile:solidity:read-file +1ms
  hardhat:core:hre Running task compile:solidity:get-compilation-jobs +2ms
  hardhat:core:tasks:compile The dependency graph was divided in '1' connected components +0ms
  hardhat:core:hre Running task compile:solidity:get-compilation-job-for-file +0ms
  hardhat:core:compilation-job File '[REDACTED]/hardhat-epipe-repro/contracts/Greeter.sol' will be compiled with version '0.4.10' +0ms
  hardhat:core:hre Running task compile:solidity:handle-compilation-jobs-failures +13ms
  hardhat:core:hre Running task compile:solidity:filter-compilation-jobs +1ms
  hardhat:core:tasks:compile '0' jobs were filtered out +14ms
  hardhat:core:hre Running task compile:solidity:merge-compilation-jobs +1ms
  hardhat:core:hre Running task compile:solidity:compile-jobs +0ms
  hardhat:core:tasks:compile Compiling 1 jobs +1ms
  hardhat:core:hre Running task compile:solidity:compile-job +0ms
  hardhat:core:tasks:compile Compiling job with version '0.4.10' +0ms
  hardhat:core:hre Running task compile:solidity:get-compiler-input +0ms
  hardhat:core:hre Running task compile:solidity:compile +0ms
  hardhat:core:hre Running task compile:solidity:solc:compile +0ms
  hardhat:core:hre Running task compile:solidity:solc:get-build +0ms
  hardhat:core:hre Running task compile:solidity:log:download-compiler-start +5ms
  hardhat:core:tasks:compile Checking native solc binary +29ms
  hardhat:core:hre Running task compile:solidity:log:download-compiler-end +91ms
  hardhat:core:hre Running task compile:solidity:log:run-compiler-start +0ms
Compiling 1 file with 0.4.10
  hardhat:core:hre Running task compile:solidity:solc:run +1ms
An unexpected error occurred:

Error: Command failed: [REDACTED]/hardhat-nodejs/compilers/macosx-amd64/solc-macosx-amd64-v0.4.10+commit.f0d539ae --standard-json
unrecognised option '--standard-json'

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '[REDACTED]/hardhat-nodejs/compilers/macosx-amd64/solc-macosx-amd64-v0.4.10+commit.f0d539ae --standard-json'
}
```

Changing the version to `0.4.11` gets the expected result.

**Comment by alcuadrado** [comment]
This is really interesting. 0.4.10 may not support this way of working with solc, and may not work at all with hardhat.

Is 0.4.10 still used in an active project?

**Comment by cameel** [comment]
`--standard-json` flag was added in 0.4.11: https://github.com/ethereum/solidity/blob/develop/Changelog.md#0411-2017-05-03.

So I guess the native binaries for earlier versions are not usable if you can only provide JSON input. I think the only option here is to use the emscripten builds for <= 0.4.10.

**Comment by alcuadrado** [comment]
That's really interesting, @cameel! Thanks. 

I thought that the standard jsons were added to the binaries and emscripten builds in the same version. Wasn't it like that?

**Comment by cameel** [comment]
It was - according to the changelog `compileStandard()` was added in that same  version - but I'm assuming that you can still give the compiler some form of JSON input in older versions. It just might be a slightly different format. This change happened long before I joined the project though so I'm not really sure how the input looked before without diving into the old code. Maybe @axic or @chriseth could shed some light on this?

**Comment by axic** [comment]
Before standard json only that "combined json" option existed.

`solc-js` has a backward compatible wrapper, so that it will use the old interfaces, but the earlier you go the less it can do (such as very early versions didn't support multiple files).  If you need to use the CLI, then this is of no help.

**Comment by alcuadrado** [comment]
Thanks for your explanations! I think we are going to print an error explaining that we don't support solidity `<= 0.4.11` for now. If enough people ask for it we can add it in the future.

**Comment by santisiri** [comment]
hi @alcuadrado, just for reference here.. the contracts of kleros live on mainnet use indeed solc 0.4.*

**Comment by ZainGulbaz** [comment]
@fvictorio Can you please assign this to me? Thanks.

**Comment by ZainGulbaz** [comment]
@fvictorio  I think this issue is already resolved.
We are getting error for version lower than 0.4.10 when we run "npx hardhat compile".

```
Error HH608: Version 0.4.10 is not supported by Hardhat.

The first supported version is 0.4.11

```
