### ISSUE TITLE
hardhat:core:hardhat-network:node  TypeError: Cannot read property 'pc' of undefined

### ISSUE THREAD

**Issue by Ximanz** [nomiclabs/hardhat#1503]
Running hardhat 2.3.0, executing a mocha/chai test with hardhat-ethers, ran into this error with one particular test case, but can't see anything problematic in my code to have caused this.  I have other tests that are almost identical but they don't cause the same error.

`hardhat:core:hardhat-network:node Could not generate stack trace. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  TypeError: Cannot read property 'pc' of undefined
    at SolidityTracer._rawTraceEvmExecution (c:\git\zero-money\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:266:70)
    at SolidityTracer._traceEvmExecution (c:\git\zero-money\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:238:29)
    at SolidityTracer._getCallMessageStackTrace (c:\git\zero-money\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:149:17)
    at SolidityTracer.getStackTrace (c:\git\zero-money\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:76:19)
    at HardhatNode._manageErrors (c:\git\zero-money\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:1269:41)
    at HardhatNode._gatherTraces (c:\git\zero-money\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:1077:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at listOnTimeout (internal/timers.js:524:9) +0ms`

**Comment by fvictorio** [comment]
Hi @Ximanz, thanks for reporting this. Is your repo public? Or can you tell us how to reproduce the issue?

**Comment by Ximanz** [comment]
My repo isn't public, but I'm basically testing a simple ERC721 contract, in particular testing the following function, which should be self explanatory:

```
function changeSupplyLimit(uint256 newSupplyLimit) public onlyOwner {
    require(totalSupply() <= newSupplyLimit, "Can't set limit below what has already been minted.");
    
    emit SupplyLimitChanged(newSupplyLimit);
    supplyLimit = newSupplyLimit;
}
```

The particular line in my test that causes this error is:
```
await expect(myContract.connect(addr1).changeSupplyLimit(10)).to.be.revertedWith("Caller is not the owner.");
```

Let me know if that's not enough information, happy to supply additional details.

**Comment by fvictorio** [comment]
That error is usually caused by a solidity construct we don't support, and that snippet looks pretty standard, so my guess is that it won't be enough. We usually need at least the whole file to be able to debug this. 

The most useful thing would be for you to remove parts of your code until you have a minimal, single Solidity file that reproduces the problem, but I know that takes a lot of time. If you can't do that, then the alternative is to share your repo privately with me.

If neither one is an option for you, then let's revisit this after the next release, because it will improve several things around the tracing and maybe it will just work.
