### ISSUE TITLE
Hardhat Network tracing engine doesn't work when mappings contain custom types (enums or contracts) as keys

### ISSUE THREAD

**Issue by JasoonS** [nomiclabs/hardhat#1564]
Thanks for the awesome tool!

## Simple reproduction of issue:

1. add a `revert()` or similar to somewhere in some hardhat contracts you have at hand. (check it shows the stack trace correctly)
2. Add this anywhere in any of your contract files (doesn't need to be the one that you added the revert to):
```solidity
enum EnumThatBreaksThings {Option1, Option2}
mapping(EnumThatBreaksThings => uint256) public thing;
```
3. Run the tests again, you won't get proper stack traces. Something like this will be shown instead:
```
at <UnrecognizedContract>.<unknown> (0xdc64a140aa3e981100a9beca4e685f962f0cf6c9)
```

## Other info:

I have run the code with the `--verbose` flag and this was the output.

```
The Hardhat Network tracing engine could not be initialized. Run Hardhat with --verbose to learn more.
  hardhat:core:hardhat-network:node Hardhat Network tracing disabled: ContractsIdentifier failed to be initialized. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  TypeError: Cannot read property 'startsWith' of undefined
    at toCanonicalAbiType (/home/jasoons/Documents/code/monorepo/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/compiler-to-model.ts:536:12)
    at getPublicVariableSelectorFromDeclarationAstNode (/home/jasoons/Documents/code/monorepo/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/compiler-to-model.ts:240:23)
    at processVariableDeclarationAstNode (/home/jasoons/Documents/code/monorepo/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/compiler-to-model.ts:282:5)
    at processContractAstNode (/home/jasoons/Documents/code/monorepo/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/compiler-to-model.ts:151:7)
    at createSourcesModelFromAst (/home/jasoons/Documents/code/monorepo/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/compiler-to-model.ts:80:9)
    at Object.createModelsAndDecodeBytecodes (/home/jasoons/Documents/code/monorepo/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/compiler-to-model.ts:37:3)
    at new HardhatNode (/home/jasoons/Documents/code/monorepo/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:297:27)
    at Function.create (/home/jasoons/Documents/code/monorepo/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:193:18)
    at HardhatNetworkProvider._init (/home/jasoons/Documents/code/monorepo/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:239:28)
    at HardhatNetworkProvider._send (/home/jasoons/Documents/code/monorepo/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:179:5) +0ms
```

**Comment by fvictorio** [comment]
Thank you for the detailed issue @JasoonS :+1:

**Comment by DenhamPreen** [comment]
Can't appreciate the work on hardhat enough, and so I hope this follow-up doesn't come up ungrateful in any sense. I just wanted to enquire if there was any roadmap on this 🙏

**Comment by fvictorio** [comment]
Hey @DenhamPreen, this is a part of the codebase in which we don't work "continually"; often it's only when we add support for newer versions of solidity, so my guess is that we'll take a look at this next time we make an effort in that direction. It's definitely on our roadmp, but I can't give an ETA, sorry.

**Comment by paulrberg** [comment]
An unfortunate side effect of this bug is that it makes it impossible for us to continue testing our contracts if they implement Solidity v0.8.4 [custom errors](https://blog.soliditylang.org/2021/04/21/custom-errors/). I will have to convert my struct keys to vanilla Solidity types for the time being.

Like @DenhamPreen, I hope that my update doesn't come up as off-putting. I love Hardhat. I just wanted to report that this GitHub issue has more implications that it seemed at first blush.

**Comment by paulrberg** [comment]
More data points. The bug does not apply if:

- The custom type keys are set in a mapping which belongs to a struct. E.g. [here](https://github.com/hifi-finance/hifi/blob/f47a808d9028c748b45ea538e307254052471f05/packages/protocol/contracts/core/balanceSheet/SBalanceSheetV1.sol#L16-L21).
- The mapping is marked as internal. E.g. [here](https://github.com/hifi-finance/hifi/blob/f47a808d9028c748b45ea538e307254052471f05/packages/protocol/contracts/core/balanceSheet/SBalanceSheetV1.sol#L32) and [here](https://github.com/hifi-finance/hifi/blob/f47a808d9028c748b45ea538e307254052471f05/packages/protocol/contracts/core/fintroller/SFintrollerV1.sol#L57-L61).

**Comment by fvictorio** [comment]
Fixed in [`hardhat@2.6.3`](https://github.com/nomiclabs/hardhat/releases/tag/hardhat%402.6.3). Thanks again, @k06a!

**Comment by cameel** [comment]
Just a heads up:  Solidity 0.8.8 adds support for user defined value types (https://github.com/ethereum/solidity/pull/11806). They're not yet allowed as mapping keys they likely will be in one of the releases after that. See https://github.com/ethereum/solidity/issues/11928 if you want to track progress on that feature.

**Comment by fvictorio** [comment]
@cameel I see there's a merged PR about that. Does that mean that the next nightly will have that feature enabled?

**Comment by cameel** [comment]
Yeah it's already implemented and merged. It went much than I expected :)

**Comment by alcuadrado** [comment]
Thanks for the heads up, @cameel!

I think they will work out of the box, as we now take advantage of the selector that is present in the public mappings' AST nodes.
