### ISSUE TITLE
HardhatError: HH502: Couldn't download complier connection list. Please check your connection ?! 

### ISSUE THREAD

**Issue by vinaypuranik** [nomiclabs/hardhat#1639]
Hi Folks, 

Getting this below error . Any possible solution ? Hardhat v2.4.1
![image](https://user-images.githubusercontent.com/6823168/124775992-c2466f00-df47-11eb-9ffc-2fa9c4724988.png)

```
HardhatError: HH502: Couldn't download compiler versions list. Please check your connection.

    at CompilerDownloader.downloadCompilersList (/app/node_modules/hardhat/src/internal/solidity/compiler/downloader.ts:186:13)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    at CompilerDownloader.getCompilersList (/app/node_modules/hardhat/src/internal/solidity/compiler/downloader.ts:159:7)

    at CompilerDownloader._fetchVersionPath (/app/node_modules/hardhat/src/internal/solidity/compiler/downloader.ts:241:16)

    at CompilerDownloader._versionExists (/app/node_modules/hardhat/src/internal/solidity/compiler/downloader.ts:259:25)

    at CompilerDownloader.getCompilerBuild (/app/node_modules/hardhat/src/internal/solidity/compiler/downloader.ts:168:9)

    at CompilerDownloader.isCompilerDownloaded (/app/node_modules/hardhat/src/internal/solidity/compiler/downloader.ts:74:27)

    at SimpleTaskDefinition.action (/app/node_modules/hardhat/src/builtin-tasks/compile.ts:489:36)

    at Environment._runTaskDefinition (/app/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)

    at Environment.run (/app/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)



    Caused by: FetchError: request to https://binaries.soliditylang.org/linux-amd64/list.json failed, reason: Client network socket disconnected before secure TLS connection was established

        at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)

        at ClientRequest.emit (node:events:394:28)

        at TLSSocket.socketErrorListener (node:_http_client:447:9)

        at TLSSocket.emit (node:events:394:28)

        at emitErrorNT (node:internal/streams/destroy:193:8)

        at emitErrorCloseNT (node:internal/streams/destroy:158:3)

        at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by alcuadrado** [comment]
Are you behind a proxy?

**Comment by fvictorio** [comment]
I'm going to assume this is a connection or a proxy issue. If you are behind a proxy, you can configure an `HTTP_PROXY` environment variable, as explained [here](https://hardhat.org/guides/compile-contracts.html#configuring-the-compiler):

> Hardhat will automatically download the versions of `solc` that you set up. If you are behind an HTTP proxy, you may need to set the `HTTP_PROXY` or `HTTPS_PROXY` environment variable to the URL of your proxy.

Please use [our Discord server](https://hardhat.org/discord) if you have more questions.

**Comment by vinaypuranik** [comment]
@alcuadrado @fvictorio  I am not behind any proxy so to speak

**Comment by vinaypuranik** [comment]
@alcuadrado @fvictorio  I checked with our network team they mentioned that we are not behind any proxy. Have Jenkins deployed on some server and trying to build the docker image. Below are the contents of Dockerfile.  
![image](https://user-images.githubusercontent.com/6823168/124899773-1ce3d780-dfe9-11eb-82e4-dd92525faa24.png)

Strange that if I build this docker image locally, it succeeds. But not on where the Jenkins server.

![image](https://user-images.githubusercontent.com/6823168/124899925-43a20e00-dfe9-11eb-80c3-f3f78b3ac876.png)
