### ISSUE TITLE
Issue with latest version of `@ethereumjs/tx`

### ISSUE THREAD

**Issue by ngotchac** [nomiclabs/hardhat#1642]
Hi,

It seems that there's an issue with the latest version of `@ethereumjs/tx`. When running a Hardhat node, sending a call via :
```bash
curl --data '{"method":"eth_call","params":[{"to":"0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b","data":"0xaa"}, "latest"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545/
```

fails with `TypeError: Cannot read property 'gteHardfork' of undefined`.

The stack trace is:
```
TypeError: Cannot read property 'gteHardfork' of undefined
    at new Transaction (/home/nicolas/Workspace/moonce/godefi/node_modules/@ethereumjs/tx/src/legacyTransaction.ts:112:17)
    at new FakeSenderTransaction (/home/nicolas/Workspace/moonce/godefi/node_modules/hardhat/src/internal/hardhat-network/provider/transactions/FakeSenderTransaction.ts:92:5)
    at HardhatNode._getFakeTransaction (/home/nicolas/Workspace/moonce/godefi/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1309:12)
    at HardhatNode.runCall (/home/nicolas/Workspace/moonce/godefi/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:417:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at EthModule._callAction (/home/nicolas/Workspace/moonce/godefi/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:347:59)
    at HardhatNetworkProvider._sendWithLogging (/home/nicolas/Workspace/moonce/godefi/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:126:22)
    at HardhatNetworkProvider.request (/home/nicolas/Workspace/moonce/godefi/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:103:18)
    at JsonRpcHandler._handleRequest (/home/nicolas/Workspace/moonce/godefi/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
    at JsonRpcHandler._handleSingleRequest (/home/nicolas/Workspace/moonce/godefi/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
```

The issue seems to be that `@ethereumjs/tx` relies on `this._validateTxV` [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/103402bedb9c0adcb649761baaacd9ad7d38ec91/packages/tx/src/legacyTransaction.ts#L105) ; whereas it is overriden by Hardhat [here](https://github.com/nomiclabs/hardhat/blob/81a1493e49db87d9741ffc69dc1f4e3d9deee47c/packages/hardhat-core/src/internal/hardhat-network/provider/transactions/FakeSenderTransaction.ts#L157).

I think one can just downgrade to the previous version of  `@ethereumjs/tx` for a temporary fix.

**Comment by ngotchac** [comment]
A couple of other `@ethereumjs` dependencies needs to be downgraded actually. This works for me:

```json

    "@ethereumjs/block": "3.3.0",
    "@ethereumjs/blockchain": "5.3.1",
    "@ethereumjs/common": "2.3.1",
    "@ethereumjs/tx": "3.2.1",
    "@ethereumjs/vm": "5.4.2"
```

**Comment by fvictorio** [comment]
@ngotchac thanks for reporting this. I just published an RC version (you can install it using `npm i hardhat@rc`) that should fix this problem. Can you try it out and let me know if it works for you?

**Comment by ngotchac** [comment]
> @ngotchac thanks for reporting this. I just published an RC version (you can install it using `npm i hardhat@rc`) that should fix this problem. Can you try it out and let me know if it works for you?

Just tried it out, and it works! :tada:
