### ISSUE TITLE
Automatic getter for mappings returns an array when mapping to structs

### ISSUE THREAD

**Issue by LuisHPorras** [nomiclabs/hardhat#1708]
## Description
- Public mapping from uint to struct inside a smart contract e.g. mapping(uint16 => BadgeInfo) public badgesById
- When using the automatically generated getter the result of calling the method is an Array with duplicated info instead of an Object

### Smart contract
[Link to file](https://github.com/LuisHPorras/web3-server/blob/smart-contracts/test/badge-test.js)
```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.0;

import "hardhat/console.sol";

contract Badge {

  address public owner = msg.sender;
  uint16 currentId = 0;
  struct BadgeInfo{
    uint16 id;
    address issuer;
    string issuerName;
    address recipient;
    string recipientName;
  }
  mapping(uint16 => BadgeInfo) public badgesById;
  event BadgeIssued(uint16 id, string issuerName, string recipientName);

  function issue(string memory _issuerName, address _recipient, string memory _recipientName) public {
    badgesById[currentId] = BadgeInfo({
      id: currentId,
      issuer: msg.sender,
      issuerName: _issuerName,
      recipient: _recipient,
      recipientName: _recipientName
    });

    emit BadgeIssued(badgesById[currentId].id, badgesById[currentId].issuerName, badgesById[currentId].recipientName);

    currentId++;
  }
}
```
### Test 
[Link to file](https://github.com/LuisHPorras/web3-server/blob/smart-contracts/contracts/Badge.sol)
```javascript
const { expect } = require("chai");

describe("Badge contract", function () {

  let owner;
  let issuer;
  let recipient;
  let badgeInfo;

  let Badge;
  let badge;

  before( async function () {

    // Save account addresses once to use in each test 
    const accounts = await ethers.getSigners();
    owner = accounts[0];
    issuer = accounts[1];
    recipient = accounts[2];

    // Badge info to use
    badgeInfo = {
      id: 0,
      issuer: issuer.address,
      issuerName: "Ivan Illich",
      recipient: recipient.address,
      recipientName: "Gustavo Esteva"
    };

  });

  beforeEach( async function () {
    
    // Deploy fresh contract before each test
    Badge = await ethers.getContractFactory("Badge");
    badge = await Badge.deploy();
    await badge.deployed();

  });

  // (...)

  it("Should return a badge", async function () {

      await badge.issue(badgeInfo.issuerName, badgeInfo.recipient, badgeInfo.recipientName);

      const badgeResult = await badge.badgesById(badgeInfo.id);
      console.log(badgeResult);

      expect(badgeResult).to.deep.equal(badgeInfo);

    });
  });
});

```

## Output
```
$ npx hardhat test


  Badge contract
    Deployment
      ✓ Should set the right owner
    Issuing
      ✓ Should emit a badge issued event (46ms)
[
  0,
  '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
  'Ivan Illich',
  '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC',
  'Gustavo Esteva',
  id: 0,
  issuer: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
  issuerName: 'Ivan Illich',
  recipient: '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC',
  recipientName: 'Gustavo Esteva'
]
      1) Should return a badge


  2 passing (666ms)
  1 failing

  1) Badge contract
       Issuing
         Should return a badge:
     AssertionError: expected [ Array(5) ] to deeply equal { Object (id, issuer, ...) }
      at Context.<anonymous> (test/badge-test.js:67:35)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at runNextTicks (internal/process/task_queues.js:64:3)
      at listOnTimeout (internal/timers.js:526:9)
      at processTimers (internal/timers.js:500:7)
```

## Steps to reproduce
1.- Clone the repo & switch to smart-contracts branch
```bash
git clone https://github.com/luishporras/web3-server
git checkout smart-contracts
```
2.- Install deps and run tests
```bash
npm install
npx hardhat test
```

## Gratitude
Thanks in advance and excuse me if it's my fault and I'm not seeing the bug.

**Comment by fvictorio** [comment]
That's actually how ethers.js works. If you have a struct like this:

```solidity
struct Point {
  uint x;
  uint y;
}
```

And you get a value of that type in ethers, then you get something that you can use both as an object and as an array. That is, assume you get a `Point(1,2)` in your test. Then:

```js
const point = await getPointFromContractSomehow()
assert.equal(point[0], 1)
assert.equal(point[1], 2)
assert.equal(point.x, 1)
assert.equal(point.y, 2)
```

I'm not sure what's the best practice to assert a result in a test when you have several properties. If I were you, I would just assert each property one by one, since it seems like the simplest approach.

Please use [our Discord server](https://hardhat.org/discord) if you have more questions.
