### ISSUE TITLE
Running `npm install --save-dev hardhat` : cannot find `'@ethersproject/abi'`

### ISSUE THREAD

**Issue by ozh** [nomiclabs/hardhat#1745]
Hello there,

Couldn't find something similar in previously open or closed issue, I hope this isn't too much of a hassle.

Following the first steps to install : 
```
npm install --save-dev hardhat
npx hardhat
```
gives me the following error : 
```
Error: Cannot find module '@ethersproject/abi'
```
<details>
  <summary>Require stack :</summary>

  ```
    Require stack:
    - D:\home\my_project\node_modules\hardhat\internal\hardhat-network\stack-traces\error-inferrer.js
    - D:\home\my_project\node_modules\hardhat\internal\hardhat-network\stack-traces\solidityTracer.js
    - D:\home\my_project\node_modules\hardhat\internal\core\config\config-loading.js
    - D:\home\my_project\node_modules\hardhat\internal\cli\cli.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
        at Function.Module._load (internal/modules/cjs/loader.js:745:27)
        at Module.require (internal/modules/cjs/loader.js:961:19)
        at require (internal/modules/cjs/helpers.js:92:18)
        at Object.<anonymous> (D:\home\my_project\node_modules\hardhat\src\internal\hardhat-network\stack-traces\error-inferrer.ts:2:1)
        at Module._compile (internal/modules/cjs/loader.js:1072:14)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
        at Module.load (internal/modules/cjs/loader.js:937:32)
        at Function.Module._load (internal/modules/cjs/loader.js:778:12)
        at Module.require (internal/modules/cjs/loader.js:961:19)
  ```
</details>

I think the module was present. Even though I did `npm i @ethersproject/abi` afterwards, but `npx hardhat` still produces the same.

Running on Windows 10, in an MSYS2 (msysgit) terminal, latest npm

**Comment by fvictorio** [comment]
First time I see that error. It's most likely something related to your setup. I recommend you try again in an empty directory, clean your npm/yarn cache, or try directly inside a docker container or VM.

If you think this is not related to your setup and have _specifc_ steps to reproduce the problem, please reopen this issue.

If you have more questions like these, please use [our Discord server](https://hardhat.org/discord).
