### ISSUE TITLE
`TypeError: Cannot read property 'call' of null` when running script in network without account

### ISSUE THREAD

**Issue by psychob** [nomiclabs/hardhat#1807]
When i tried to run simple script that only calls view methods of some smart contract, it fails with following exception:

```
TypeError: Cannot read property 'call' of null
    at Object.<anonymous> ([redacted]/node_modules/@ethersproject/contracts/src.ts/index.ts:329:47)
    at step ([redacted]/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next ([redacted]/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled ([redacted]/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Current Result

After some digging around, i noticed that when i add any account to my network setting (e.g.: test address used in hardhat) it starts working as expected:

```js
    mainnet: {
      url: 'https://mainnet.infura.io/v3/[redacted[',
      accounts: {
        mnemonic: "test test test test test test test test test test test junk"
      }
    }
```

If accounts key is omitted, commented out, or it is empty array, it fails when running script.

My `package.json`:
```json
{
  "name": "hardhat-project",
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.2",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "chai": "^4.3.4",
    "ethereum-waffle": "^3.4.0",
    "ethers": "^5.4.4",
    "hardhat": "^2.6.0",
    "hardhat-deploy": "^0.8.11",
    "prettier": "^2.3.2",
    "prettier-plugin-solidity": "^1.0.0-beta.17",
    "solidity-coverage": "git+ssh://git@github.com/psychob/solidity-coverage.git"
  },
  "dependencies": {
    "@openzeppelin/contracts": "^3.4.1",
    "@uniswap/v2-periphery": "^1.1.0-beta.0",
    "dotenv": "^10.0.0"
  }
}

```

### Expected Result

Either:

1. Script will fail at configuration phase, that account is required
2. Script will run as expected, and only fail if method we are trying to run modifies state of blockchain

**Comment by fvictorio** [comment]
Hi @psychob, this doesn't seem to have enough information to reproduce it. Please create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so we can look into it.
