### ISSUE TITLE
The faulty Line of the test script is not covered in the stack trace for misusing signer for address

### ISSUE THREAD

**Issue by branaway** [nomiclabs/hardhat#1816]
The contract function requires an address as the parameter. The following stack trace was displayed when I mistakenly put a signer object in place of the address.  The stack trace did not show the faulty line of the test js script. 

   Error: invalid ENS name (argument="name", value="<SignerWithAddress 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266>", code=INVALID_ARGUMENT, version=providers/5.4.4)
      at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
      at Logger.throwArgumentError (node_modules/@ethersproject/logger/src.ts/index.ts:229:21)
      at EthersProviderWrapper.<anonymous> (node_modules/@ethersproject/providers/src.ts/base-provider.ts:1565:20)
      at step (node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
      at Object.next (node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
      at fulfilled (node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at runNextTicks (internal/process/task_queues.js:64:3)
      at listOnTimeout (internal/timers.js:526:9)
      at processTimers (internal/timers.js:500:7)

**Comment by branaway** [comment]
Perhaps hardhat can be made smarter to take either an address or a signer in cases where an address is required for a parameter. Writing <signer>.address is tedious.

**Comment by fvictorio** [comment]
Hi @branaway, I think this is an issue for [ethers.js](https://github.com/ethers-io/ethers.js/), but AFAIK the author is already aware of this limitation and will make this more flexible in the next release (v6), where you'll be able to use wallets and contracts instances where an address is expected.
