### ISSUE TITLE
ProviderError: method handler crashed when connecting to a Quorum Network

### ISSUE THREAD

**Issue by cdesch** [nomiclabs/hardhat#1827]
I get `ProviderError: method handler crashed` error when I connect to a [Quorum](https://consensys.net/quorum/) network. Connecting with `ethers`  via the regular method works fine.

Error: 
```
ProviderError: method handler crashed
    at HttpProvider.request (C:\Projects\my-project\node_modules\hardhat\internal\core\providers\http.js:50:23)
    at LocalAccountsProvider.request (C:\Projects\my-project\node_modules\hardhat\internal\core\providers\accounts.js:117:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async EthersProviderWrapper.send (C:\Projects\my-project\node_modules\@nomiclabs\hardhat-ethers\internal\ethers-provider-wrapper.js:11:24)
```

Connecting to the same Quorum Node via `ethers` that works:

```
const provider = new ethers.providers.JsonRpcProvider(
    MY_QUORUM_NODE_ADDRESS
  );
```

The error occurs when I run a script with the `HARDHAT_NETWORK` env set for the `hardhat.config.js`. For example, my `hardhat.config.js`:

```
...
module.exports = {
  solidity: '0.8.5',
  networks: {
    hardhat: {},
    myquorum: {
      url: MY_QUORUM_NODE_ADDRESS,
      chainId: 1101,
      from: '0x0000000....',
      accounts: [
        '0x0000000....',
      ],
    },
  },
};
```

Then running the script:

`HARDHAT_NETWORK=myquorum node scripts/deploy-my-contract.js`

Why is this happening with HardHat and not `ethers`?

**Comment by cdesch** [comment]
@fvictorio Not really. [Quorum](https://consensys.net/quorum/) is a fork of Ethereum and used for private networks. Not a big deal though because you can still compile and test contracts with hardhat and then deploy them with `ethers` separately.
