### ISSUE TITLE
Issues with using --network localhost

### ISSUE THREAD

**Issue by zendevil** [nomiclabs/hardhat#1870]
There are a few issues when I use --network localhost with npx hardhat test:

1. console.log doesn't show.
I have imported hardhat/console.log and use it like so:
```
    function totalAmountRaised() public view returns (uint) {
        uint totalRaised = 0;
        for (uint i = 0; i < initialStakesList.length; i++) {
            totalRaised += initialStakes[initialStakesList[i]];
            console.log("stake of %s: %s", 
                        initialStakesList[i], initialStakes[initialStakesList[i]]);
        }
        return totalRaised;
    }
```

Here's the test:
```
const YieldToken = artifacts.require("YieldToken");
const { expect } = require("chai");
const { ethers } = require("hardhat");

describe("YieldToken", function () {
    it("buying, giving up, minting and payouts with ethers", 
        async function () {
            const YieldToken = await ethers.getContractFactory("YieldToken");
            const yieldToken = await YieldToken.deploy("ipfs", 1, 1, 1, 1, 1, 1, 1);
            await yieldToken.deployed();

            const signers = await ethers.getSigners();
            yieldToken.connect(signers[1]).buyStake({value: 1000});
            yieldToken.connect(signers[2]).buyStake({value: 2000});
            yieldToken.connect(signers[3]).buyStake({value: 3000});
            yieldToken.connect(signers[4]).buyStake({value: 4000});
            yieldToken.connect(signers[5]).buyStake({value: 5000});
            yieldToken.connect(signers[6]).buyStake({value: 6000});
                 


            raised = await yieldToken.connect(signers[1]).totalAmountRaised();
            expect(raised.toNumber()).to.equal(21000);

        });
});
```

but I don't see anything logs from the totalAmountRaised call when using --network localhost, but do without it. 

2. The test doesn't pass when it should.
When I use --network localhost, the test fails and gives this output:
     ```
       1) YieldToken
       buying, giving up, minting and payouts with ethers:

      AssertionError: expected 0 to equal 21000
      + expected - actual

      -0
      +21000

      at Context.<anonymous> (test/YieldToken.js:23:42)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      ```
      But it passes when --network localhost isn't used.

FWIW all transactions show up in the hardhat node logs.

**Comment by Kayaba-Attribution** [comment]
Perhaps you need to await for the transactions when using .buystake() ?

**Comment by fvictorio** [comment]
> 1. console.log doesn't show.

The logs will show up in the terminal where you are running the node, not in the one that is running the tests.

> 2. The test doesn't pass when it should.

As @Kayaba-Attribution mentioned, that's probably because you are missing some `await`s.

Please use [our Discord server](https://hardhat.org/discord) if you have more questions, since the issue tracker is only for bug reports or feature requests.
