### ISSUE TITLE
Could not generate stacktrace error

### ISSUE THREAD

**Issue by grapevinegizmos** [nomiclabs/hardhat#1874]
You've asked me to report, herewith stack trace. 

This was the result of running npx hardhat test --verbose

The test fails with an out of gas error, although I assume this error just refers to the inability to provie a stack trace, not with wny the test is failing for not enough gas.e
 

```
hardhat:core:hardhat-network:node Could not generate stack trace. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  Error: There's no instruction at pc 162
    at Bytecode.getInstruction (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/model.ts:329:13)
    at SolidityTracer._rawTraceEvmExecution (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:174:37)
    at SolidityTracer._traceEvmExecution (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:149:29)
    at SolidityTracer._getCreateMessageStackTrace (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:132:17)
    at SolidityTracer.getStackTrace (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:52:19)
    at HardhatNode._manageErrors (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1705:41)
    at HardhatNode.estimateGas (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:661:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at listOnTimeout (internal/timers.js:526:9) +0ms
    1) "before each" hook for "should instantiate..."
```

**Comment by fvictorio** [comment]
Hey @grapevinegizmos, can you give us a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? Or, if you don't know how to do it or don't want to, can you tell us how to reproduce it in your repo, assuming it's public?
