### ISSUE TITLE
ProviderError: invalid argument 1: json: cannot unmarshal hex string of odd length into Go value of type hexutil.Bytes

### ISSUE THREAD

**Issue by DZariusz** [nomiclabs/hardhat#1896]
When I forked Arbitrum, run a test and I want to do a call to view method I got error: `ProviderError: invalid argument 1: json: cannot unmarshal hex string of odd length into Go value of type hexutil.Bytes`

**test example:**

```ts
describe('Arbitrum Contract', function () {
  before(forkToArbitrum)

  it('expects to get data', async function () {
    await deployments.fixture();
    const deployed = await deployments.get('Contract');

    const contract = new Contract(
      deployed.address,
      deployed.abi,
      (await ethers.getSigners())[0]
    );
    
    await contract.getData('0x6c9fc64a53c1b71fb3f9af64d1ae3a4931a5f4e9', 0, 2);
  });
});
```

**error:**

```shell
ProviderError: invalid argument 1: json: cannot unmarshal hex string of odd length into Go value of type hexutil.Bytes
    at HttpProvider.request (node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
    at JsonRpcClient._send (node_modules/hardhat/src/internal/hardhat-network/jsonrpc/client.ts:319:39)
    at JsonRpcClient._perform (node_modules/hardhat/src/internal/hardhat-network/jsonrpc/client.ts:249:34)
    at JsonRpcClient.getStorageAt (node_modules/hardhat/src/internal/hardhat-network/jsonrpc/client.ts:55:17)
    at ForkStateManager.getContractStorage (node_modules/hardhat/src/internal/hardhat-network/provider/fork/ForkStateManager.ts:206:51)
    at EEI.storageLoad (node_modules/@ethereumjs/vm/src/evm/eei.ts:372:26)
    at i (node_modules/@ethereumjs/vm/src/evm/opcodes/functions.ts:746:40)
    at Interpreter.runStep (node_modules/@ethereumjs/vm/src/evm/interpreter.ts:152:38)
    at Interpreter.run (node_modules/@ethereumjs/vm/src/evm/interpreter.ts:113:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at EVM.runInterpreter (node_modules/@ethereumjs/vm/src/evm/evm.ts:482:28)
    at EVM._executeCall (node_modules/@ethereumjs/vm/src/evm/evm.ts:281:16)
    at EVM.executeMessage (node_modules/@ethereumjs/vm/src/evm/evm.ts:172:16)
    at EEI._baseCall (node_modules/@ethereumjs/vm/src/evm/eei.ts:538:21)
    at i (node_modules/@ethereumjs/vm/src/evm/opcodes/functions.ts:1178:19)
    at Interpreter.runStep (node_modules/@ethereumjs/vm/src/evm/interpreter.ts:152:7)
    at Interpreter.run (node_modules/@ethereumjs/vm/src/evm/interpreter.ts:113:9)
    at EVM.runInterpreter (node_modules/@ethereumjs/vm/src/evm/evm.ts:482:28)
    at EVM._executeCall (node_modules/@ethereumjs/vm/src/evm/evm.ts:281:16)
    at EVM.executeMessage (node_modules/@ethereumjs/vm/src/evm/evm.ts:172:16)
    at VM._runTx (node_modules/@ethereumjs/vm/src/runTx.ts:356:20)
    at VM.runTx (node_modules/@ethereumjs/vm/src/runTx.ts:182:20)
    at HardhatNode._runTxAndRevertMutations (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:2157:14)
    at HardhatNode.runCall (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:498:20)
    at EthModule._callAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:353:9)
    at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:108:18)
    at EthersProviderWrapper.send (node_modules/hardhat-deploy-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

hardhat v2.6.4

Solution is to use even hex for `eth_getStorageAt` call.

I will provide PR that fixes it shortly.

The #1897 fix forks for:
- [x] Polygon
- [x] Arbitrum
- [ ] Ethereum (not tested, but there is high chance it is working as well because it is working for Polygon)

**Comment by alcuadrado** [comment]
Please take a look at #1902

**Comment by alcuadrado** [comment]
BTW, we can't switch this to send even length hex strings, as all the other nodes expect these values to be odd when needed.

**Comment by DZariusz** [comment]
well, this fix works on Polygon, I assume it will work on Ethereum as well (but I did not test it on Ethereum). So looks like it is not true that **all other** nodes expect this. 
@alcuadrado please note important thing - my fix set even length **ONLY FOR** `position`.

**Comment by alcuadrado** [comment]
As mentioned in the PR, the Arbitrum team mentioned that they consider this a bug on their end and are fixing it.
