### ISSUE TITLE
HardhatError: HH5: HardhatContext is not created.

### ISSUE THREAD

**Issue by dancju** [nomiclabs/hardhat#1930]
Executing this TypeScript file in `/scripts`

```ts
import "@nomiclabs/hardhat-web3";
```

or this file

```ts
import "@nomiclabs/hardhat-waffle";
```

yields this error.

```
$ yarn run ts-node scripts/sample-script
yarn run v1.22.15
$ $HOME/tmp/node_modules/.bin/ts-node scripts/sample-script
$HOME/tmp/node_modules/hardhat/src/internal/context.ts:37
      throw new HardhatError(ERRORS.GENERAL.CONTEXT_NOT_CREATED);
            ^
HardhatError: HH5: HardhatContext is not created.
    at Function.getHardhatContext ($HOME/tmp/node_modules/hardhat/src/internal/context.ts:37:13)
    at Object.extendEnvironment ($HOME/tmp/node_modules/hardhat/src/internal/core/config/config-env.ts:128:30)
    at Object.<anonymous> ($HOME/tmp/node_modules/@nomiclabs/hardhat-web3/src/index.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> ($HOME/tmp/scripts/sample-script.ts:1:1) {
  parent: undefined,
  errorDescriptor: {
    number: 5,
    message: 'HardhatContext is not created.',
    title: "Hardhat wasn't initialized",
    description: 'Hardhat initialization failed. This is a bug.\n' +
      '\n' +
      'Please [report it](https://github.com/nomiclabs/hardhat/issues/new) to help us improve Hardhat.',
    shouldBeReported: true
  },
  number: 5,
  messageArguments: {},
  _isHardhatError: true
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by fvictorio** [comment]
Plugins are meant to be imported in the `hardhat.config.ts` file, not in scripts or tests. Check [our docs](https://hardhat.org/getting-started/) to learn more.
