### ISSUE TITLE
Can't send real mainnet tx to forked mainnet

### ISSUE THREAD

**Issue by dancju** [nomiclabs/hardhat#1932]
I am trying to replicate the historical txs on a forked mainnet.

When I was sent a real historical (with original signature) tx through `sendTransaction`, it reports that the chainIds do not agree.

```
Error: Incompatible EIP155-based V 37 and chain id 31337. See the Common parameter of the Transaction constructor to set the chain id.
```

Is there anyway I can send a real mainnet tx to a forked mainnet?

**Comment by alcuadrado** [comment]
Are you using `eth_sendRawTransaction`?

You should set the `chainId` to `1`

**Comment by dancju** [comment]
> Are you using `eth_sendRawTransaction`?
> 
> You should set the `chainId` to `1`

I am using `waffle.provider.sendTransaction`.
Yes, I am trying to set the `chainId`. Can I set it in code instead of in the config file?

**Comment by fvictorio** [comment]
> Can I set it in code instead of in the config file?

To prevent the EIP-155 check from failing, you need to set it in the config. Since you are re-playing transactions (or at least that's what I understood), those txs might include a `chainId` of 1, which is then "compared" to the one in the network.

The alternative would be to re-play the txs with a chain id of 31337, but that's probably not what you want.

**Comment by dancju** [comment]
> To prevent the EIP-155 check from failing, you need to set it in the config. Since you are re-playing transactions (or at least that's what I understood), those txs might include a `chainId` of 1, which is then "compared" to the one in the network.
> 
> The alternative would be to re-play the txs with a chain id of 31337, but that's probably not what you want.

Thank you for replying! Yes changing the `chainId` of the chain would be better. If we change the `chainId` of the tx, the original signature would be invalid, then I'll have to use `hardhat_impersonateAccount`.

May I ask another question here? I successfully re-playing 100-ish txs. There was one tx just can't be replayed.

```
{
  to: '0x169332Ae7D143E4B5c6baEdb2FEF77BFBdDB4011',
  from: '0xC6C36027878Ba38964E4D5A60Ddb20D09565354E',
  contractAddress: null,
  transactionIndex: 1,
  gasUsed: BigNumber { _hex: '0xe644', _isBigNumber: true },
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000100000000000000000000000000000000000000000010000000000000000000000000200400000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  blockHash: '0xe1c353752c83ffc7779ecdd8569cd06a590a6ef4ced99c41d0279a5b00a6bf69',
  transactionHash: '0x3a3edc9554047b344079bc292d781fdea7b331d43549de86e1032d10bc00eabc',
  logs: [
    {
      transactionIndex: 1,
      blockNumber: 12038871,
      transactionHash: '0x3a3edc9554047b344079bc292d781fdea7b331d43549de86e1032d10bc00eabc',
      address: '0x169332Ae7D143E4B5c6baEdb2FEF77BFBdDB4011',
      topics: [Array],
      data: '0x000000000000000000000000000000000000000000000000000000000000000f0000000000000000000000000000000000000000000000000000000000000017',
      logIndex: 0,
      blockHash: '0xe1c353752c83ffc7779ecdd8569cd06a590a6ef4ced99c41d0279a5b00a6bf69'
    }
  ],
  blockNumber: 12038871,
  confirmations: 1322384,
  cumulativeGasUsed: BigNumber { _hex: '0x027838', _isBigNumber: true },
  effectiveGasPrice: BigNumber { _hex: '0x482d709c00', _isBigNumber: true },
  status: 1,
  type: 0,
  byzantium: true
}
```

Here is the error msg.

```
TransactionExecutionError: Transaction ran out of gas
    at HardhatNode._manageErrors (/home/dan/git/tmp/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1738:14)
    at HardhatNode._gatherTraces (/home/dan/git/tmp/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1468:30)
    at async HardhatNode._mineBlockWithPendingTxs (/home/dan/git/tmp/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1582:23)
    at async HardhatNode.mineBlock (/home/dan/git/tmp/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:435:16)
    at async EthModule._sendTransactionAndReturnHash (/home/dan/git/tmp/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1494:18)
    at async HardhatNetworkProvider.request (/home/dan/git/tmp/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:108:18)
    at async EthersProviderWrapper.send (/home/dan/git/tmp/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
error Command failed with exit code 1.
```
