### ISSUE TITLE
Tx reverted without a reason string

### ISSUE THREAD

**Issue by dancju** [nomiclabs/hardhat#1935]
I am trying to replicate this transaction, which was reverted on the main chain due to being out of gas.
https://etherscan.io/tx/0x8544e64257d79e6725d053117baec4c23ea968211c89cc6b78b3e1b1a7e27c04

But Hardhat reported `Transaction reverted without a reason string` instead of `out of gas`.

I am doing it with the right hard fork `muirGlacier`.

**Reproduction steps**

```ts
  await hre.network.provider.request({
    method: "hardhat_reset",
    params: [{ forking: { jsonRpcUrl: PROVIDER } }],
  });
  const block = await ethers.provider.getBlockWithTransactions(BLOCK);
  const txs = block.transactions;
  const txs_raw = block.transactions.map(getRawTransaction);

  await hre.network.provider.request({
    method: "hardhat_reset",
    params: [{
      forking: { jsonRpcUrl: PROVIDER, blockNumber: BLOCK - 1 }
    }],
  });
  let tx_raw = txs_raw[73];
  let tx_mock = await ethers.provider.sendTransaction(tx_raw);
  let receipt = await tx_mock.wait();
  console.log(receipt);
```

```
$ ts-node --files scripts/main.ts
Error: Transaction reverted without a reason string
    at <UnrecognizedContract>.<unknown> (0x2647bd8777e0c66819d74ab3479372ea690912c3)
    at <UnrecognizedContract>.<unknown> (0x3c06b757e24815f2dcd71baa9516bca2d691f8fc)
    at async HardhatNode._mineBlockWithPendingTxs (/home/dan/git/tmp/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1582:23)
    at async HardhatNode.mineBlock (/home/dan/git/tmp/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:435:16)
    at async EthModule._sendTransactionAndReturnHash (/home/dan/git/tmp/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1494:18)
    at async HardhatNetworkProvider.request (/home/dan/git/tmp/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:108:18)
    at async EthersProviderWrapper.send (/home/dan/git/tmp/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by spaceh3ad** [comment]
Have same issue, after lending wFTM to scWFTM, and wanted to check balance:

`    console.log(await scWFTM.balanceOf(deployerAddress));
`

```
       Should lend wFTM and borrow scWFTM:
     Error: Transaction reverted without a reason string
      at <UnrecognizedContract>.<unknown> (0x5aa53f03197e08c4851cad8c92c7922da5857e5d)
      at <UnrecognizedContract>.<unknown> (0x5aa53f03197e08c4851cad8c92c7922da5857e5d)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)
      at async EthModule._estimateGasAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:108:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

**Comment by fvictorio** [comment]
@spaceh3ad that means that the transaction reverted and there wasn't a reason string in the code. That is, you hit a:

```solidity
require(falseCondition)
```

statement. That's not an error in Hardhat, it just means that you triggered a revert. You'll have to inspect the code of the involved contracts to figure out what happened. The stack trace at least gives you a hint: the revert happened in the contract at address `0x5aa53f03197e08c4851cad8c92c7922da5857e5d`.
