### ISSUE TITLE
`HARDHAT_TESTS_SOLC_PATH` does not work with absolute paths

### ISSUE THREAD

**Issue by cameel** [nomiclabs/hardhat#1969]
I'm working on https://github.com/ethereum/solidity/issues/10854 to run Hardhat's test suite as a part of Solidity CI. The problem I encountered is that when I specify an absolute path to the compiler binary in `HARDHAT_TESTS_SOLC_PATH`, Hardhat still uses it as if it was relative to the directory where it keeps downloaded compiler binaries. The resulting path does not exist and hardhat tries to download the binary from solc-bin, which fails too because that path's not on the server either.

This looks like a bug to me because the original instructions in the issue included an absolute path as an example. Also, I would like to stop Hardhat from trying to download the compiler automatically because I want to be sure that the binary I give it is the only one it could be using. Automatic download could easily hide potential problems by testing the wrong binary.

### Details
```bash
curl https://binaries.soliditylang.org/bin/soljson-v0.8.4+commit.c7e474f2.js -L -o /tmp/soljson.js
git clone --depth 1 https://github.com/nomiclabs/hardhat.git
cd hardhat
yarn
yarn build

cd packages/hardhat-core/
HARDHAT_TESTS_SOLC_VERSION="0.8.4" \
HARDHAT_TESTS_SOLC_PATH="/tmp/soljson.js" \
yarn test
```
Relevant parts of the output:
```
  Stack traces
    Use compiler at /tmp/soljson.js with version 0.8.4
```
```
  0 passing (23s)
  5 pending
  253 failing

  1) Stack traces
       Use compiler at /tmp/soljson.js with version 0.8.4
         0_8
           abi-v2
             call-failing-function
               Without optimizations
                 test-files/0_8/abi-v2/call-failing-function:
     Error: Failed to download https://solc-bin.ethereum.org/bin//tmp/soljson.js - Not Found received
      at Object.download (src/internal/util/download.ts:55:9)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at downloadSolc (test/internal/hardhat-network/stack-traces/compilation.ts:110:3)
      at getSolc (test/internal/hardhat-network/stack-traces/compilation.ts:114:3)
      at compile (test/internal/hardhat-network/stack-traces/compilation.ts:127:16)
      at compileIfNecessary (test/internal/hardhat-network/stack-traces/test.ts:237:43)
      at runTest (test/internal/hardhat-network/stack-traces/test.ts:408:43)
      at Context.func (test/internal/hardhat-network/stack-traces/test.ts:136:5)
```

### Workaround
My current workaround is to create a symlink to the binary in `packages/hardhat-core/test/internal/hardhat-network/stack-traces/compilers` and put only the file name in the variable.

**Comment by cameel** [comment]
Great! Fortunately the workaround does help so we can run with that until a fix is released.

I already managed to run tests in CI and I see [two failing](https://app.circleci.com/pipelines/github/ethereum/solidity/19877/workflows/a8840c31-1a7a-4047-9914-2221c1191c10/jobs/879015) on the latest binary but looks like you already have a PR fixing that (#1962) so hopefully we'll have that running on our side pretty soon. On 0.8.4 all tests pass.

**Comment by cameel** [comment]
One more thing (slightly related): the [`run-tests-with-custom-solc.sh`](https://github.com/nomiclabs/hardhat/blob/master/scripts/run-tests-with-custom-solc.sh) script seems to be missing a `yarn build` invocation. Without it I get an exception due to a problem with a relative import somewhere deep in the package.

I'm not reporting it as a separate issue because I'm not sure if it makes sense to fix it. The script is pretty simple and in our CI I just repeated the relevant commands - this way I can have dependency installation and actual tests as separate steps. So it was useful as way to tell us what specifically to run but I don't think we'll be using it after that.
