### ISSUE TITLE
Implement personal_sign in Hardhat Network

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#1981]
As mentioned in #1972, ethers now uses this method, so we should implement it now.

**Comment by fvictorio** [comment]
Added in `hardhat@2.6.8`.

**Comment by mds1** [comment]
It seems this is only supported for signers included in the default hardhat config, which makes sense. I have some fuzz tests that use ethers' `Wallet.createRandom()` to generate random wallets to sign with `personal_sign`, and impersonating them is of course not sufficient since the provider doesn't have the private key. 

I could increase the number of initial accounts or randomize the mnemonic/path used, but this feels a little clunky. One solution is to update `hardhat_impersonateAccount` to take a private key instead of an address, but curious if you had any other thoughts

**Comment by mds1** [comment]
Worth noting that these tests were previously using `wallet.signMessage`, which it seems did not require a request to the provider, so there might be a workaround within ethers that I should look into also

**Comment by fvictorio** [comment]
@mds1 My guess is that you are doing something like this, right?

```js
wallet = ethers.Wallet.createRandom()
await hre.network.provider.send("hardhat_impersonateAccount", [wallet.address])
signer = await ethers.getSigner(wallet.address)
signedMessage = await signer.signMessage("foo")
```

In that case, no, this won't work. But if you use `wallet.signMessage` instead, that will work because the wallet has access to the private key.

**Comment by mds1** [comment]
Yep, that's what I'm doing and totally understand why it doesn't work!

Mainly asked about impersonating via private key or other ideas because I thought `signMessage` didn't add the message prefix, whereas `personal_sign` does, so they'd give different signatures. Though maybe the behavior of `signMessage` has changed since I last looked

**Comment by fvictorio** [comment]
Hmm, I get the same result if I use the default signer (which uses `personal_sign`) and if I create a wallet with the private key of that signer and sign the same message.

**Comment by mds1** [comment]
Ah ok, so I looked at the code and (1) the Hardhat implementation of `eth_sign`, (2) the Hardhat implementation of `personal_sign`, and (3) ethers' `signMessage`, all add the message prefix. (Not all `eth_sign` implementations add the prefix).

As a result, these three signing approaches are all equivalent with Hardhat + ethers

```typescript
// hardhat account 0 with default mnemonic and path path: "m/44'/60'/1'/0"
const signerE = new ethers.Wallet('0x7797c0f3db8b946604ec2039dfd9763e4ffdc53174342a2ed9b14fa3eda666a5'); 
const [signerH] = await ethers.getSigners();
if (signerH.address !== signerE.address) throw new Error('Address mismatch');

const provider = ethers.provider;
const { hexlify, toUtf8Bytes } = ethers.utils;

const message = 'Sign this message to access your account';
const formattedMessage = hexlify(toUtf8Bytes(message));
const addr = signerH.address.toLowerCase()

const sigH_ps = String(await provider.send('personal_sign', [formattedMessage, addr]));
const sigH_es = String(await provider.send('eth_sign', [addr, formattedMessage]));
const sigE = String(await signerE.signMessage(message));

console.log('sig hardhat personal_sign: ', sigH_ps);
console.log('sig hardhat eth_sign:      ', sigH_es);
console.log('sig ethers signMessage:    ', sigE);
```

So you are right, I can just continue to use ethers' `signMessage` here. Thanks a lot @fvictorio!

**Comment by BKopyIo** [comment]
is there some reason why signMessage works in tests on the transient node, but fails with "personal_sign - Method not supported" when run on a localhost persistent node?

In my tests I use `let sig = await signer.signMessage(ethers.utils.arrayify(hashSource));`

which works fine when I run it a spec with hh test;
but when I use the same thing with `run script/test.ts --network localhost` I get all this:

`ProviderError: Method personal_sign not found
    at HttpProvider.request (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
    at AutomaticSenderProvider.request (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/internal/core/providers/accounts.ts:351:34)
    at AutomaticGasProvider.request (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:136:34)
    at AutomaticGasPriceProvider.request (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:153:36)
    at BackwardsCompatibilityProviderAdapter.send (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/internal/core/providers/backwards-compatibility.ts:36:27)
    at EthersProviderWrapper.send (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:48)
    at JsonRpcSigner.<anonymous> (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:295:36)
    at step (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.next (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at fulfilled (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:20:58)`

**Comment by fvictorio** [comment]
@BKopyIo I started a `npx hardhat node` and then connected to it with `--network localhost` and the method is present. Maybe you are connecting to a different node?

**Comment by BKopyIo** [comment]
Hm. Puzzling.  I started a new npx node on my terminal, as well, and just wrote a single test using signer.signMessage(string) using hh test –network localhost and got the same failure.


From: Franco Victorio ***@***.***>
Reply-To: NomicFoundation/hardhat ***@***.***>
Date: Thursday, August 18, 2022 at 3:28 AM
To: NomicFoundation/hardhat ***@***.***>
Cc: Josh Kramer ***@***.***>, Mention ***@***.***>
Subject: Re: [NomicFoundation/hardhat] Implement personal_sign in Hardhat Network (Issue #1981)


@BKopyIo<https://github.com/BKopyIo> I started a npx hardhat node and then connected to it with --network localhost and the method is present. Maybe you are connecting to a different node?
