### ISSUE TITLE
Add MoonRiver & Moonbase Alpha support to hardhat-etherscan's verify plugin

### ISSUE THREAD

**Issue by fullyallocated** [nomiclabs/hardhat#2067]
Hi, I'm deploying contracts to Moonbase Alpha/Moonriver and I'm having a hard time verifying the contracts using hardhat-etherscan because of the lack of native support.

Can we add the following networks to the prober.ts file: https://github.com/nomiclabs/hardhat/blob/d905f66896351a99df964ac7f481b0bf52f282d5/packages/hardhat-etherscan/src/network/prober.ts

MOONBASE_ALPHA: 1287   -> https://moonbase.moonscan.io/
MOONRIVER: 1285 -> https://moonscan.io/

Thank you!

**Comment by fullyallocated** [comment]
Seems like there's an open PR for this: #2046

**Comment by fvictorio** [comment]
Yes, we're waiting for Etherscan to properly support these chains before merging it, otherwise we can't test that the PR works.

**Comment by kabaluyot** [comment]
Waiting for this .. Very important for mass adoption of moonriver

**Comment by fvictorio** [comment]
Released in `@nomiclabs/hardhat-etherscan@2.1.8`.

**Comment by kabaluyot** [comment]
Hi @fvictorio, where can I secure the correct API key? I tried using my existing etherscan API key (which I use in eth and bsc) but returns `Invalid API Key` ..

Compiling 1 file with 0.8.9
NomicLabsHardhatPluginError: Invalid API Key
    at Object.verifyContract (/Users/karlanthonybaluyot/Documents/nuxify/nftdeals-blocsport1/nfts/node_modules/@nomiclabs/hardhat-etherscan/src/etherscan/EtherscanService.ts:68:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at attemptVerification (/Users/karlanthonybaluyot/Documents/nuxify/nftdeals-blocsport1/nfts/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:441:20)
    at SimpleTaskDefinition.action (/Users/karlanthonybaluyot/Documents/nuxify/nftdeals-blocsport1/nfts/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:738:48)
    at Environment._runTaskDefinition (/Users/karlanthonybaluyot/Documents/nuxify/nftdeals-blocsport1/nfts/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/karlanthonybaluyot/Documents/nuxify/nftdeals-blocsport1/nfts/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.verifySubtask [as action] (/Users/karlanthonybaluyot/Documents/nuxify/nftdeals-blocsport1/nfts/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:281:28)
    at Environment._runTaskDefinition (/Users/karlanthonybaluyot/Documents/nuxify/nftdeals-blocsport1/nfts/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/karlanthonybaluyot/Documents/nuxify/nftdeals-blocsport1/nfts/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at main (/Users/karlanthonybaluyot/Documents/nuxify/nftdeals-blocsport1/nfts/scripts/deploy_auction_house.js:41:3)

**Comment by kabaluyot** [comment]
Moonscan API works with Moonriver but returns `Invalid API Key` when deploying for Moonbase Alpha

**Comment by fvictorio** [comment]
> Moonscan API key works with Moonriver with above's version but returns `Invalid API Key` when deploying for Moonbase Alpha

Yes, that's expected. The Etherscan folks are working on this, and when that's fixed on their side, this version should work fine. See [this comment](https://github.com/nomiclabs/hardhat/pull/2046#issuecomment-976695183)

**Comment by villarode** [comment]
Still can't verify my contract on Moonbase Alpha:

Error HH303: Unrecognized task verify

**Comment by fvictorio** [comment]
> Error HH303: Unrecognized task verify

That usually means that you are not importing the plugin in your config.

**Comment by lee-rand** [comment]
I am still getting  `NomicLabsHardhatPluginError: Invalid API Key` when using  `"@nomiclabs/hardhat-etherscan": "^3.0.0"`

Any clue on whether hardhat verify plugging works properly for Moonbase? Thanks

**Comment by kabaluyot** [comment]
Did you check your moonscan API key?

**Comment by lee-rand** [comment]
Yes @kabaluyot. I got my api key from `https://moonbeam.moonscan.io/`. Is that what you mean?

**Comment by kabaluyot** [comment]
Should be good then. The last time I checked it, it worked with `"@nomiclabs/hardhat-etherscan": "^2.1.8",`
