### ISSUE TITLE
Testnet POLYGON RPC Nodes  HH110: Invalid JSON-RPC response received

### ISSUE THREAD

**Issue by qq335103060** [nomiclabs/hardhat#2105]
hardhat.config.js：
matictestnet: {
        url: 'https://rpc-mumbai.maticvigil.com',
        accounts: [],
        chainId: 80001
}
await upgrades.erc1967.getAdminAddress("") ro await upgrades.upgradeProxy(",);
HardhatError: HH110: Invalid JSON-RPC response received: {"error":{"details":"Internal RPC Error. Try again after some time..","code":-32005},"jsonrpc":"2.0","id":8}
    at Object.parseJsonResponse (xxnode_modules/hardhat/src/internal/util/jsonrpc.ts:47:11)
    at HttpProvider._fetchJsonRpcResponse (/xx/node_modules/hardhat/src/internal/core/providers/http.ts:173:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HttpProvider.request (xx/node_modules/hardhat/src/internal/core/providers/http.ts:55:29)
    at getStorageAt (xx/node_modules/@openzeppelin/upgrades-core/src/provider.ts:47:19)
    at getStorageFallback (xx/node_modules/@openzeppelin/upgrades-core/src/eip-1967.ts:46:15)
    at getAdminAddress (xx/node_modules/@openzeppelin/upgrades-core/src/eip-1967.ts:7:19)
    at main (xx/scripts/proxyAdmin.js:6:34)

**Comment by RMartires** [comment]
im getting the same problem, the error msg keeps changing tho

i get HH109: Network connection timed out.

**Comment by RMartires** [comment]
i get this error too:
HH110: Invalid JSON-RPC response received:

**Comment by RMartires** [comment]
yo it works with this url: https://matic-mumbai.chainstacklabs.com

**Comment by fvictorio** [comment]
It seems like the remote node is having/had some issues. See the error message:

> Internal RPC Error. Try again after some time..
