### ISSUE TITLE
hardhat-etherscan`ERC1967Proxy` fail

### ISSUE THREAD

**Issue by gigamesh** [nomiclabs/hardhat#2117]
I'm not sure if this is a bug with `hardhat-etherscan` or a bug with Etherscan but I haven't been able to consistently verify an `ERC1967Proxy`. The implementation verifies, but not the proxy. Any ideas?

```
Successfully verified contract ArtistCreator on Etherscan.
https://rinkeby.etherscan.io/address/0xDE76497e40F69d4ae50f7E2Ae1e20e9a6B2c95D8#code
Verifying proxy: 0x8e9794C65Ccf6f5C47eea20D5489f05EF5C65419

Successfully submitted source code for contract
contracts/ArtistCreatorProxy.sol:ArtistCreatorProxy at 0x8e9794C65Ccf6f5C47eea20D5489f05EF5C65419
for verification on Etherscan. Waiting for verification result...

We tried verifying your contract ArtistCreatorProxy without including any unrelated one, but it failed.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...

Successfully submitted source code for contract
contracts/ArtistCreatorProxy.sol:ArtistCreatorProxy at 0x8e9794C65Ccf6f5C47eea20D5489f05EF5C65419
for verification on Etherscan. Waiting for verification result...

NomicLabsHardhatPluginError: The contract verification failed.
Reason: Fail - Unable to verify
    at SimpleTaskDefinition.verifySubtask [as action] (/Users/masurka/SOUND_XYZ/sound-collective/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:330:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Environment._runTaskDefinition (/Users/masurka/SOUND_XYZ/sound-collective/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at async Environment.run (/Users/masurka/SOUND_XYZ/sound-collective/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
```

Proxy code:
```
pragma solidity ^0.8.7;

import '@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol';

contract ArtistCreatorProxy is ERC1967Proxy {
    constructor(
        address _logic,
        address,
        bytes memory _data
    ) payable ERC1967Proxy(_logic, _data) {}
}
```

**Comment by alcuadrado** [comment]
Hey @gigamesh, 

Were both contracts deployed at the same time? did you modify your codebase after deploying them? If not, this looks like an issue with Etherscan.

**Comment by gigamesh** [comment]
Thanks @alcuadrado 

For anyone who finds this in the future, The issue was that I was mistakenly retrieving the beacon address and trying to initialize that, rather than the implementation. You need to instantiate the UpgradeableBeacon contract with the correct address, then call `implementation()` on it to get the implementation address.
