### ISSUE TITLE
Several large smart contracts cause `RangeError: Invalid string length` in JSON.stringify

### ISSUE THREAD

**Issue by citizen-stig** [nomiclabs/hardhat#2165]
# Intro
I have a private Ethereum setup, which has large limit for contract size and large limit for gas per block. I would like to deploy smart contracts there using hardhat.

# Steps to Reproduce

1. Clone repo https://github.com/citizen-stig/hardhat-large-contracts-compilation
2. Run `npm install`
3. Run `npx hardhat compile`

# Expected Results

All contracts are compiled

# Actual Result

Compilation fails with

```
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at stringify (/Users/ngolub/workspace/hardhat-large-compile/node_modules/jsonfile/index.js:86:18)
    at Object.writeFile (/Users/ngolub/workspace/hardhat-large-compile/node_modules/jsonfile/index.js:101:11)
    at /Users/ngolub/workspace/hardhat-large-compile/node_modules/universalify/index.js:13:12
    at new Promise (<anonymous>)
    at Object.writeFile (/Users/ngolub/workspace/hardhat-large-compile/node_modules/universalify/index.js:7:14)
    at Artifacts.saveBuildInfo (/Users/ngolub/workspace/hardhat-large-compile/node_modules/hardhat/src/internal/artifacts.ts:166:19)
    at SimpleTaskDefinition.action (/Users/ngolub/workspace/hardhat-large-compile/node_modules/hardhat/src/builtin-tasks/compile.ts:793:31)
    at Environment._runTaskDefinition (/Users/ngolub/workspace/hardhat-large-compile/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/ngolub/workspace/hardhat-large-compile/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
 ```
 
 # Environment
 
```
npx hardhat --version
2.8.0
node --version
v16.13.1
```

MacOS, but same result is on Linux

**Comment by fvictorio** [comment]
This seems important. Thanks @citizen-stig for the reproduction example.

There seems to be a limit in V8 that causes `JSON.stringify` to not work with large inputs. We might need to move from plain `JSON.parse`/`JSON.stringify` to some module for doing these operations with streams.

**Comment by citizen-stig** [comment]
> This seems important. Thanks @citizen-stig for the reproduction example.
> 
> There seems to be a limit in V8 that causes `JSON.stringify` to not work with large inputs. We might need to move from plain `JSON.parse`/`JSON.stringify` to some module for doing these operations with streams.

Thank you Franco for picking this up.

I don't know internals of hardhat, but I've noticed that problem is not in single large smart contract, but combinations of them. So if one smart contract is removed, it will pass, even if this smart contract is not largers.
Maybe batching stringification per smart contract might help and be good quick fix.

**Comment by fvictorio** [comment]
Not stale.

**Comment by python481516** [comment]
not stale

**Comment by hadfieldn** [comment]
not stale

**Comment by MasonTDaniel** [comment]
experiencing this issue still

**Comment by fvictorio** [comment]
Uhm, I don't know why the bot is not working here.

**Comment by peebeejay** [comment]
we are on it

**Comment by fvictorio** [comment]
That makes sense! I guess what I would've expected is that a GitPOAP assigned through a comment will simply give a POAP for this year. In fact, I would expect that even for merged PRs that were started in a different year.

**Comment by peebeejay** [comment]
yea - i agree completely here!
