### ISSUE TITLE
tsconfig short paths are not working

### ISSUE THREAD

**Issue by LukeSamkharadze** [nomiclabs/hardhat#2259]
My `tsconfig.json`

```JSON
{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "outDir": "dist",
    "declaration": true,
    "resolveJsonModule": true,
    "baseUrl": ".",
    "paths": {
      "@built-contracts/*": ["artifacts/contracts/*"]
    }
  }
}
```

Here is my `contracts/utils/SummitReferral.test.ts` file. Btw when I `ctrl` + `left click` the path `@built-contracts/utils/WBNB.sol/WBNB.json` it resolves file correctly

```TS
import { expect, assert } from "chai";
import { Contract, utils } from "ethers";
import WETH from "@built-contracts/utils/WBNB.sol/WBNB.json";
```

`VS Code` has a little red squiggly as well, but it resolves path correctly when I hover the mouse

![image](https://user-images.githubusercontent.com/31849767/149449559-89359b29-02e3-45e8-a579-f71943bc1037.png)

Output when running `hardhat test`

```
> hardhat test

No need to generate any newer typings.
An unexpected error occurred:

Error: Cannot find module '@built-contracts/utils/WBNB.sol/WBNB.json'
Require stack:
- /home/luke/repos/dx/summitswap-contracts/test/SummitReferral.test.ts
- /home/luke/repos/dx/summitswap-contracts/node_modules/mocha/lib/mocha.js
- /home/luke/repos/dx/summitswap-contracts/node_modules/mocha/index.js
- /home/luke/repos/dx/summitswap-contracts/node_modules/hardhat/builtin-tasks/test.js
- /home/luke/repos/dx/summitswap-contracts/node_modules/hardhat/internal/core/tasks/builtin-tasks.js
- /home/luke/repos/dx/summitswap-contracts/node_modules/hardhat/internal/core/config/config-loading.js
- /home/luke/repos/dx/summitswap-contracts/node_modules/hardhat/internal/cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/luke/repos/dx/summitswap-contracts/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/luke/repos/dx/summitswap-contracts/test/SummitReferral.test.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/home/luke/repos/dx/summitswap-contracts/node_modules/ts-node/src/index.ts:1371:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/home/luke/repos/dx/summitswap-contracts/node_modules/ts-node/src/index.ts:1374:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/luke/repos/dx/summitswap-contracts/test/SummitReferral.test.ts',
    '/home/luke/repos/dx/summitswap-contracts/node_modules/mocha/lib/mocha.js',
    '/home/luke/repos/dx/summitswap-contracts/node_modules/mocha/index.js',
    '/home/luke/repos/dx/summitswap-contracts/node_modules/hardhat/builtin-tasks/test.js',
    '/home/luke/repos/dx/summitswap-contracts/node_modules/hardhat/internal/core/tasks/builtin-tasks.js',
    '/home/luke/repos/dx/summitswap-contracts/node_modules/hardhat/internal/core/config/config-loading.js',
    '/home/luke/repos/dx/summitswap-contracts/node_modules/hardhat/internal/cli/cli.js'
  ]
}
```

I tried to use `tsconfig` paths in isolated/seperate project as well and it worked perfectly, maybe something is causing this issue in this project?

**Comment by kanej** [comment]
I was able to reproduce this error on a new hardhat (v2.8.2) typescript sample project, by adding the typescript paths in tsconfig and attempting to refer to contract output in the sample test.

`npx hardhat test` shows the error above. A run of `tsc --traceResolution | grep @built-contracts` shows that pure typescript is able to resolve the json file:

![image](https://user-images.githubusercontent.com/24030/149754899-293bfe3f-0093-47ac-8566-2a14d3cc2c7d.png)

The error must be either somewhere else in typescript or in the interplay between mocha, module resolution and typescript.

**Comment by kanej** [comment]
Hey @LukeSamkharadze, to use typescript paths in hardhat you need to register the `tsconfig-paths/register` module in your hardhat config. You can find the details in the hardhat docs:

https://hardhat.org/guides/typescript.html#support-for-path-mappings

**Comment by LukeSamkharadze** [comment]
@kanej thanks a lot, it worked. I totally missed that
