### ISSUE TITLE
HardhatError: HH5 - what can I do?

### ISSUE THREAD

**Issue by ChrisFarey** [nomiclabs/hardhat#2264]
```js
/**
* @type import('hardhat/config').HardhatUserConfig
*/
require('dotenv').config();
require("@nomiclabs/hardhat-ethers");
const { API_URL, PRIVATE_KEY } = process.env;
module.exports = {
   solidity: "0.8.2",
   defaultNetwork: "ropsten",
   networks: {
      hardhat: {},
      ropsten: {
         url: API_URL,
         accounts: [`0x${PRIVATE_KEY}`]
      }
   },
}
```

```
"HardhatError: HH5: HardhatContext is not created.
    at Function.getHardhatContext (/Users/christianfriedrich/Documents/NFTMinting/my-nft/node_modules/hardhat/internal/context.js:35:19)
    at extendEnvironment (/Users/christianfriedrich/Documents/NFTMinting/my-nft/node_modules/hardhat/internal/core/config/config-env.js:60:42)
    at Object.<anonymous> (/Users/christianfriedrich/Documents/NFTMinting/my-nft/node_modules/@nomiclabs/hardhat-ethers/internal/index.js:13:32)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/christianfriedrich/Documents/NFTMinting/my-nft/hardhat.config.js:5:1) {
  parent: undefined,
  errorDescriptor: {
    number: 5,
    message: 'HardhatContext is not created.',
    title: "Hardhat wasn't initialized",
    description: 'Hardhat initialization failed. This is a bug.\n' +
      '\n' +
      'Please [report it](https://github.com/nomiclabs/hardhat/issues/new) to help us improve Hardhat.',
    shouldBeReported: true
  },
  number: 5,
  messageArguments: {},
  _isHardhatError: true
}"
```

**Comment by fvictorio** [comment]
This normally happens when you execute the hardhat config (e.g., `node hardhat.config.js`), or you execute some module that requires the config. Instead of doing that, you should use the Hardhat command (`npx hardhat compile`, for example).
