### ISSUE TITLE
Testing of basic contract fails

### ISSUE THREAD

**Issue by inflation-man** [nomiclabs/hardhat#2340]
I had a few issues when testing my smart contracts. First it would estimate that basic smart contract function calls would run out of gas, when I overrode the gas limit, it would either loop infinitely when deployed to a hardhat node or throw the following error when tested.
```
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (./test/testMapping.spec.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```
I have reduced my repository further and further until I was left with this. The code runs fine with remix, but fails when tested with hardhat.
MappingContract.sol
```
pragma solidity = 0.8.11;

contract MappingContract{
    mapping(uint256 => uint256) internal identity;

    function addNumber(uint256 number) external{
        identity[number] = number;
    }

    function getIdentity(uint256 number) external returns (uint256 numberOut){
        numberOut = identity[number];
    }

    constructor() {
        identity[0] = 0;
    }
}
```
testMapping.spec.ts
```
const { waffle } = require('hardhat');
const { ethers } = require('hardhat');
const { expect } = require('chai');

const { Contract, Wallet, BigNumber } = ethers;
const { MockProvider, deployContract } = waffle;

const overrides = {
    gasLimit: 13000000
};

describe('Mapping Test', () => {

    it('test', async () => {
        const signers = await ethers.getSigners();
        let owner = signers[0];

        let mAddress= await ethers.getContractFactory("MappingContract");

        let m = await mAddress.deploy();

        let result = await m.getIdentity(0);
        
    });
});
```
package.json
```
{
  "name": "MappingTest",
  "version": "1.1.0-beta.0",
  "description": "Mapping Tests",
  "engines": {
    "node": ">=10"
  },
  "files": [
    "build",
    "contracts"
  ],
  "dependencies": {},
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.4",
    "@nomiclabs/hardhat-waffle": "^2.0.2",
    "chai": "^4.2.0",
    "ethereum-waffle": "^3.4.0",
    "ethers": "^5.5.4",
    "hardhat": "2.8.3",
    "mocha": "^6.2.2",
    "typescript": "^3.7.3"
  },
  "scripts": {
    "compile": "yarn hardhat compile",
    "test": "yarn mocha test/testMapping.spec.ts"
  },
  "license": "GPL-3.0-or-later"
}
```
hardhat.config.js
```
require('@nomiclabs/hardhat-ethers');
require('@nomiclabs/hardhat-waffle');

module.exports = {
  networks: {
      hardhat: {
          mining: {
              auto: false,
              interval: 5000,
          },
          blockGasLimit: 13000000,
          gasPrice: 20
      },
  },
  
  solidity: {
      compilers:[
          {
              version: "0.8.11"
          }
      ]
  }
};
```

**Comment by inflation-man** [comment]
My bad
https://ethereum.stackexchange.com/questions/120957/hardhat-basic-test-fails
