### ISSUE TITLE
HardhatError: HH600: Compilation failed

### ISSUE THREAD

**Issue by iqbal045** [nomiclabs/hardhat#2384]
Compiling 15 files with 0.8.4
Unknown key "enable"
Error HH600: Compilation failed

HardhatError: HH600: Compilation failed
    at SimpleTaskDefinition.action (/mnt/Projects/nft-kryptobirdz/node_modules/hardhat/src/builtin-tasks/compile.ts:763:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Environment._runTaskDefinition (/mnt/Projects/nft-kryptobirdz/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/mnt/Projects/nft-kryptobirdz/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/mnt/Projects/nft-kryptobirdz/node_modules/hardhat/src/builtin-tasks/compile.ts:985:7)
    at Environment._runTaskDefinition (/mnt/Projects/nft-kryptobirdz/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/mnt/Projects/nft-kryptobirdz/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/mnt/Projects/nft-kryptobirdz/node_modules/hardhat/src/builtin-tasks/compile.ts:398:45)
    at Environment._runTaskDefinition (/mnt/Projects/nft-kryptobirdz/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/mnt/Projects/nft-kryptobirdz/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)

**Comment by iqbal045** [comment]
I found that solution. i have wrong configuration in hardhat.config.js
