### ISSUE TITLE
Compilation fails with an unclear error message

### ISSUE THREAD

**Issue by vporton** [nomiclabs/hardhat#600]
https://github.com/vporton/courts-exchange/tree/55b60ba60d20ce2baac8fad6627abfe490be6741

Compilation fails with an unclear error message, it is unclear which fragment of my code causes the error:
```
$ yarn compile --show-stack-traces
yarn run v1.22.4
$ buidler compile --force --show-stack-traces
Compiling...
UnimplementedFeatureError: 

Error BDLR600: Compilation failed

Error: BDLR600: Compilation failed
    at SimpleTaskDefinition.action (/home/porton/Projects/courts-exchange/node_modules/@nomiclabs/buidler/src/builtin-tasks/compile.ts:161:13)
    at Environment._runTaskDefinition (/home/porton/Projects/courts-exchange/node_modules/@nomiclabs/buidler/src/internal/core/runtime-environment.ts:196:14)
    at SimpleTaskDefinition.action (/home/porton/Projects/courts-exchange/node_modules/@nomiclabs/buidler/src/builtin-tasks/compile.ts:204:31)
    at Environment._runTaskDefinition (/home/porton/Projects/courts-exchange/node_modules/@nomiclabs/buidler/src/internal/core/runtime-environment.ts:196:14)
    at Environment._runTaskDefinition (/home/porton/Projects/courts-exchange/node_modules/@nomiclabs/buidler/src/internal/core/runtime-environment.ts:196:14)
    at main (/home/porton/Projects/courts-exchange/node_modules/@nomiclabs/buidler/src/internal/cli/cli.ts:151:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by alcuadrado** [comment]
Thanks for reporting this @vporton. It seems to be a bug in the version of Solidity that you are using. There's more info about it here: https://github.com/ethereum/solidity/issues/3199
