### ISSUE TITLE
Build with -s ASSERTIONS=1 for more info.

### ISSUE THREAD

**Issue by minton1** [nomiclabs/hardhat#630]
```
  1) Coin Contract
       Deployment should assign the total supply of coin to be in cCoin cash:
     Uncaught RuntimeError: abort(Error: VM Exception while processing transaction: revert ds-math-sub-underflow). Build with -s ASSERTIONS=1 for more info.
      at process.abort (node_modules/@ethereum-waffle/compiler/node_modules/solc/soljson.js:1:14382)
      at process.emit (node_modules/source-map-support/source-map-support.js:495:21)
      at process.emit (node_modules/ganache-cli/node_modules/source-map-support/source-map-support.js:465:21)
      at process.object.process.function.process.on.process.emit (node_modules/ganache-cli/build/ganache-core.node.cli.js:37:31967)
      at process.emit (node_modules/ganache-core/node_modules/source-map-support/source-map-support.js:465:21)
      at processPromiseRejections (internal/process/promises.js:139:20)
      at processTicksAndRejections (internal/process/task_queues.js:87:32)
```

Pato:
"apparently, it's an error generated by emscriptem, the compiler that solc uses to build solcjs"

`> at process.abort (node_modules/@ethereum-waffle/compiler/node_modules/solc/soljson.js:1:14382)
`
"This line of your stack trace is weird"
"We don't use waffle's compiler"
"Can you open an issue describing your setup?"

```
import { BuidlerConfig, usePlugin, task, types } from "@nomiclabs/buidler/config";

usePlugin("@nomiclabs/buidler-waffle");
usePlugin("buidler-typechain");
usePlugin("@nomiclabs/buidler-web3");
usePlugin("@nomiclabs/buidler-truffle5");
usePlugin("@nomiclabs/buidler-ethers");
usePlugin("@nomiclabs/buidler-etherscan");
usePlugin("solidity-coverage");

/* ============== CONFIG ============== */

const config: BuidlerConfig = {
  defaultNetwork: "buidlerevm",
  networks: {
    buidlerevm: {
      gas: 1000000000, // high
      blockGasLimit: 1000000000, // high
      allowUnlimitedContractSize: true,
    },
    <withheld>: {
      gas: 1000000000, // high
      blockGasLimit: 1000000000, // high
      allowUnlimitedContractSize: true,
      url: 'http://127.0.0.1:8545',
    },
  },
  solc: {
    version: "0.6.8",
    optimizer: {enabled: false, runs: 20}
  },
  typechain: {
    outDir: "typechain",
    target: "ethers",
  },
};

```
run with
`npx buidler test
`
which runs the compiler if things aren't compiled already, compiler is normally run with 
`npx buidler compile
`

**Comment by fvictorio** [comment]
Hi @minton1, sorry for not responding to this before. I'm cleaning up old issues so I'm tentatively closing this one. But please re-open if this is still valid in Hardhat.
