### ISSUE TITLE
Error: invalid response - 0 when connecting to Buidler EVM with ethers v4

### ISSUE THREAD

**Issue by pcowgill** [nomiclabs/hardhat#681]
```ts
// ethers.test.ts

import { ethers } from "ethers";

const provider = new ethers.providers.JsonRpcProvider("http://localhost:8545");
provider.pollingInterval = 50;

describe("ethers", () => {
  let wallet;

  beforeEach(async () => {
    [wallet] = accounts; // let's not worry about where this came from for this example
    wallet = wallet.connect(provider);
  });


  it.only("should get balance of wallet", async () => {
    let randomWallet = ethers.Wallet.createRandom();
    
    const walletBalance = await wallet.getBalance();
    randomWallet = randomWallet.connect(provider);
    const randomWalletBalance = await randomWallet.getBalance();

});
```

| dep | version |
| ---- | ---- |
| node | v12.18.0 |
| npm | 6.14.5 |
| ethers | 4.0.47 |
| buidler | "^1.3.6" |
| solc | 0.6.9 |

`builder.config.js`: pretty much the default other than `accounts` which shouldn't matter here

```
      {
        error: Error: invalid response - 0
            at Object.<anonymous>.exports.XMLHttpRequest.request.onreadystatechange (/Users/paulcowgill/Code/tasitlabs/core/tasit-sdk/packages/account/node_modules/ethers/utils/web.js:84:29)
            at Object.<anonymous>.exports.XMLHttpRequest.dispatchEvent (/Users/paulcowgill/Code/tasitlabs/core/tasit-sdk/packages/account/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
            at setState (/Users/paulcowgill/Code/tasitlabs/core/tasit-sdk/packages/account/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
            at Object.<anonymous>.exports.XMLHttpRequest.handleError (/Users/paulcowgill/Code/tasitlabs/core/tasit-sdk/packages/account/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:532:5)
            at ClientRequest.errorHandler (/Users/paulcowgill/Code/tasitlabs/core/tasit-sdk/packages/account/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:459:14)
            at ClientRequest.emit (events.js:315:20)
            at Socket.socketErrorListener (_http_client.js:426:9)
            at Socket.emit (events.js:315:20)
            at emitErrorNT (internal/streams/destroy.js:92:8)
            at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
            at processTicksAndRejections (internal/process/task_queues.js:84:21) {
          statusCode: 0,
          responseText: 'Error: connect ECONNREFUSED 127.0.0.1:8545\n' +
            '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)'
        }
      }
```

**Comment by pcowgill** [comment]
@alcuadrado I pushed up what I thought was a reproduction here, but I'm not running into the issue, so that's good news. I'll have to see what doesn't match this setup where I was encountering the issue. https://github.com/pcowgill/buidler-evm-ethers-v4

**Comment by fvictorio** [comment]
Hey @pcowgill. I'm cleaning up old issues, so I'm going to close this one since I'm not sure if it's still valid. Please re-open if it is.
