### ISSUE TITLE
The Buidler EVM tracing engine could not be initialized

### ISSUE THREAD

**Issue by CodeSandwich** [nomiclabs/hardhat#924]
I can't get the EVM tracing engine to work, it prints this error:
```
The Buidler EVM tracing engine could not be initialized. Run Buidler with --verbose to learn more.
  buidler:core:buidler-evm:node Buidler EVM tracing disabled: ContractsIdentifier failed to be initialized. Please report this to help us improve Buidler.
  buidler:core:buidler-evm:node  TypeError: Cannot read property 'startsWith' of undefined
    at toCanonicalAbiType (/home/zuczek/workspace/radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/stack-traces/compiler-to-model.ts:474:12)
    at astFunctionDefinitionToSelector (/home/zuczek/workspace/radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/stack-traces/compiler-to-model.ts:453:21)
    at processFunctionDefinitionAstNode (/home/zuczek/workspace/radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/stack-traces/compiler-to-model.ts:179:9)
    at processContractAstNode (/home/zuczek/workspace/radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/stack-traces/compiler-to-model.ts:126:7)
    at createSourcesModelFromAst (/home/zuczek/workspace/radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/stack-traces/compiler-to-model.ts:80:7)
    at Object.createModelsAndDecodeBytecodes (/home/zuczek/workspace/radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/stack-traces/compiler-to-model.ts:32:3)
    at new BuidlerNode (/home/zuczek/workspace/radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/provider/node.ts:322:25)
    at Function.create (/home/zuczek/workspace/radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/provider/node.ts:228:18)
    at BuidlerEVMProvider._init (/home/zuczek/workspace/radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/provider/provider.ts:269:28)
    at BuidlerEVMProvider._send (/home/zuczek/workspace/radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/provider/provider.ts:188:5) +0ms
```
Is it solvable on our side? It asks to report this error to you.

To reproduce this issue you can clone https://github.com/radicle-dev/radicle-contracts, branch `verbose`, and run the regular `yarn install --frozen-lockfile && yarn run test`.

**Comment by alcuadrado** [comment]
Hey @CodeSandwich,

Can you check that you are using the latest version of Buidler? We fixed a but related to this a few weeks ago.

**Comment by CodeSandwich** [comment]
I'm running on 1.4.3, but upgrading to 1.4.8 doesn't make any difference.

**Comment by alcuadrado** [comment]
Thanks, @CodeSandwich! 

We are about to put out a big release, so we make take some time to review this. Will get back to this asap.

**Comment by CodeSandwich** [comment]
This might be fixed in hardhat :thinking: I'm not getting this warning whenever running the tests. I'm also getting clear cause and stack traces inside the contracts whenever a transaction is reverted.
