### ISSUE TITLE
"invalid opcode" when reading chain id from inline assembly

### ISSUE THREAD

**Issue by PaulRBerg** [nomiclabs/hardhat#952]
## Expected Behavior

The chain id should be accessible via inline assembly, [as this is a feature available since solidity 0.5.12][1].

## Current Behavior

The [function][2] that attempts to read the chain id fails with the following error:

```
Error: VM Exception while processing transaction: invalid opcode
  at HttpProvider.send (node_modules/@nomiclabs/buidler/src/internal/core/providers/http.ts:36:34)
  at /Users/paulrberg/Workspace/Pad/buidler-invalid-opcode/node_modules/@nomiclabs/buidler/src/internal/core/providers/gas-providers.ts:115:21
  at Proxy.cloningSendWrapper (node_modules/@nomiclabs/buidler/src/internal/core/providers/wrapper.ts:9:12)
  at /Users/paulrberg/Workspace/Pad/buidler-invalid-opcode/node_modules/@nomiclabs/buidler/src/internal/core/providers/accounts.ts:219:21
  at Proxy.cloningSendWrapper (node_modules/@nomiclabs/buidler/src/internal/core/providers/wrapper.ts:9:12)
  at /Users/paulrberg/Workspace/Pad/buidler-invalid-opcode/node_modules/@nomiclabs/buidler/src/internal/core/providers/gas-providers.ts:63:21
  at Proxy.cloningSendWrapper (node_modules/@nomiclabs/buidler/src/internal/core/providers/wrapper.ts:9:12)
  at /Users/paulrberg/Workspace/Pad/buidler-invalid-opcode/node_modules/@nomiclabs/buidler/src/internal/core/providers/gas-providers.ts:41:21
  at Proxy.cloningSendWrapper (node_modules/@nomiclabs/buidler/src/internal/core/providers/wrapper.ts:9:12)
  at EthersProviderWrapper.send (node_modules/@nomiclabs/buidler-ethers/src/ethers-provider-wrapper.ts:13:48)
  at EthersProviderWrapper.<anonymous> (node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:439:31)
  at step (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:46:23)
  at Object.next (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:27:53)
  at /Users/paulrberg/Workspace/Pad/buidler-invalid-opcode/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:71
  at new Promise (<anonymous>)
  at __awaiter (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:17:12)
```

## Steps to Reproduce

1. Clone [paulrberg/buidler-invalid-opcode][3]
2. Install dependencies with yarn
3. Generate artifacts with `yarn run typechain`
4. Run the tests with `yarn run test` and get the same error as above

## Context

As explained in this [comment][4], this issue occurs only when the `@nomiclabs/buidler-ganache` is activated. When the tests are run against an instance of `ganache-cli` running in parallel, there is no "invalid opcode" error.

I haven't checked whether this has been solved with Hardhat.

## Your Environment

* @nomiclabs/buidler@1.4.8
* @nomiclabs/buidler-ganache@1.3.3
* ganache-cli@6.9.0
* node@12.16.3
* macOS@10.15.7

[1]: https://ethereum.stackexchange.com/questions/56749/retrieve-chain-id-of-the-executing-chain-from-a-solidity-contract/76764#76764
[2]: https://github.com/PaulRBerg/buidler-invalid-opcode/blob/ff3cce91324fe1eab046e8bd9831a4a352de584b/contracts/ChainIdReader.sol#L7-L13
[3]: https://github.com/paulrberg/buidler-invalid-opcode
[4]: https://github.com/trufflesuite/ganache-core/issues/654#issuecomment-715928058

**Comment by alcuadrado** [comment]
Thanks, @PaulRBerg! I think this is a bug in how we initialize it in the plugin. Will address it soon.

**Comment by PaulRBerg** [comment]
Great, thanks for confirming, @alcuadrado.

**Comment by fvictorio** [comment]
This is indeed an issue in `hardhat-ganache`.

The fix seems simple: add `istanbul` (and whatever other hardforks are missing) to the `hardfork` option validator, and then set the `hardfork` to `istanbul`. Maybe we should also update the default value, but I'm not sure if that counts as a breaking change.

**Comment by alcuadrado** [comment]
This is a recurrent question I have. It's unclear if bumping the hardhfork of the network should actually be a breaking change, given that the users normally think of the default value as being "latest mainnet HF".

**Comment by fvictorio** [comment]
Yeah, I agree. And even if it is a breaking change, it would break things only in extremely edge cases. I don't think it makes sense to be overly rigid with that.
